const CURRICULUM = {
  phases: [
    { id:"bachelor", index:"1. Phase · B.Ed.", title:"Bachelor of Education", subtitle:"Grundlagen erschließen und erproben", modules:[
      {id:"arbeitskunde",short:"Arbeitskunde",lp:5,semester:"1"},
      {id:"berufskunde",short:"Berufskunde",lp:5,semester:"2"},
      {id:"berufspaedagogik-i",short:"Berufspädagogik I",lp:5,semester:"2"},
      {id:"technikdidaktik-grundlagen",short:"Technikdidaktik I",lp:5,semester:"3",cluster:"ba-option-1",clusterLabel:"Option 1",links:["begleitetes-sps-i"]},
      {id:"begleitetes-sps-i",short:"Begleitetes SPS I",lp:5,semester:"3",cluster:"ba-option-1",clusterLabel:"Option 1",links:["technikdidaktik-grundlagen"]},
      {id:"technikdidaktik-grundlagen-option-2",short:"Technikdidaktik I",lp:5,semester:"3",cluster:"ba-option-2",clusterLabel:"Option 2"},
      {id:"sps-i",short:"SPS I · an einer anderen Schule",lp:5,semester:"3",cluster:"ba-option-2",clusterLabel:"Option 2"},
      {id:"digitalisierung",short:"Digitalisierung in der beruflichen Bildung",lp:5,semester:"4"},
      {id:"forschungsseminar-ba",short:"Forschungsseminar · bei Bachelorarbeit",lp:null,meta:"Optional",semester:"5"},
      {id:"bachelorarbeit",short:"Bachelorarbeit",lp:null,meta:"Option",semester:"6"}
    ]},
    { id:"master", index:"1. Phase · M.Ed.", title:"Master of Education", subtitle:"Komplexität gestalten und reflektieren", modules:[
      {id:"technikdidaktik-i",short:"Technikdidaktik II",lp:5,semester:"1"},
      {id:"berufspaedagogik-ii",short:"Berufspädagogik II",lp:5,semester:"1",pair:"Tandem A",cluster:"ma-tandem-a",clusterLabel:"Zusammengehöriges Tandem",links:["sps-ii"]},
      {id:"sps-ii",short:"SPS II",lp:5,semester:"1",pair:"Tandem A",cluster:"ma-tandem-a",clusterLabel:"Zusammengehöriges Tandem",links:["berufspaedagogik-ii"]},
      {id:"technikdidaktik-ii",short:"Technikdidaktik III",lp:5,semester:"2",pair:"Tandem B",cluster:"ma-tandem-b",clusterLabel:"Zusammengehöriges Tandem",links:["fachdidaktisches-praktikum"],areas:["subjective","practice"]},
      {id:"fachdidaktisches-praktikum",short:"Fachdidaktisches Praktikum",lp:5,semester:"2",pair:"Tandem B",cluster:"ma-tandem-b",clusterLabel:"Zusammengehöriges Tandem",links:["technikdidaktik-ii"],areas:["subjective","practice"]},
      {id:"qualitaet-team",short:"Qualitäts- und Teamentwicklung",lp:5,semester:"1",transversal:true},
      {id:"forschungsseminar-ma",short:"Forschungsseminar · bei Masterarbeit",lp:null,meta:"Optional",semester:"3"},
      {id:"masterarbeit",short:"Masterarbeit",lp:null,meta:"Option",semester:"4"}
    ]},
    {
      id:"referendariat",
      index:"2. Phase · Bayern",
      title:"Referendariat",
      subtitle:"Professionell handeln",
      modules:[],
      compactItems:[
        {eyebrow:"1. Ausbildungsjahr",title:"Seminarschule",text:"Referenzrahmen · Module · Unterricht"},
        {eyebrow:"2. Ausbildungsjahr",title:"Einsatzschule",text:"Eigenverantwortlich unterrichten"},
        {eyebrow:"Abschluss",title:"Zweite Staatsprüfung",text:"Lehrproben · Kolloquium · mündlich"}
      ],
      detail:{
        kicker:"2. Phase · Bayern · 24 Monate · Referenzrahmen als Leitlinie",
        title:"Vorbereitungsdienst für das Lehramt an beruflichen Schulen",
        text:"Der bayerische Vorbereitungsdienst führt wissenschaftlich fundierte Planung und Reflexion in zunehmend eigenverantwortliches berufsschulisches Handeln. Er umfasst zwei jeweils einjährige Ausbildungsabschnitte. Der Referenzrahmen des Staatlichen Studienseminars schafft dafür verbindliche, bayernweit abgestimmte Kompetenzziele.",
        sections:[
          {title:"Referenzrahmen · Anschluss an das Studium",text:"Die im Studium aufgebauten Kompetenzen werden im Vorbereitungsdienst in fünf professionellen Handlungsfeldern konkretisiert und unter schulischem Handlungsdruck weiterentwickelt.",items:["Unterrichten: Unterricht fachlich und didaktisch planen, berufs- und lebensweltbezogen durchführen und systematisch reflektieren","Erziehen und Integrieren: Werte vermitteln, Diversität anerkennen sowie Konflikten präventiv und konstruktiv begegnen","Beraten und Beurteilen: Lernvoraussetzungen diagnostizieren, individuell fördern, adressatengerecht beraten und Leistungen transparent beurteilen","Verwalten und Organisieren: rechtssicher handeln, Verantwortung für schulische Prozesse übernehmen und mit Betrieben sowie weiteren Partnern kooperieren","Gestalten und Innovieren: Unterricht, Schulleben und Schulentwicklung auf Grundlage beruflicher, gesellschaftlicher und wissenschaftlicher Entwicklungen mitgestalten","Übergreifend: die eigene Persönlichkeit sowie digitale und medienbezogene Lehrkompetenz kontinuierlich entwickeln"]},
          {title:"1. Ausbildungsjahr · Seminarschule",text:"Die Ausbildung findet an einer oder mehreren Seminarschulen und am Staatlichen Studienseminar statt. Fachseminare, Hospitationen, Unterrichtsversuche, Beratung und Reflexion führen in die Schulpraxis ein. Das erste Halbjahr ist in der Regel frei von der Verpflichtung zu eigenverantwortlichem Unterricht."},
          {title:"2. Ausbildungsjahr · Einsatzschule",text:"An der Einsatzschule werden pädagogische, fachdidaktische und methodische Erfahrungen erweitert. Studienreferendarinnen und Studienreferendare gewinnen durch eigenverantwortlichen beziehungsweise zusammenhängenden Unterricht Sicherheit; vorgesehen sind bis zu zehn Wochenstunden, davon grundsätzlich mindestens sechs eigenverantwortlich."},
          {title:"Zweite Staatsprüfung",text:"Die professionelle Handlungsfähigkeit wird unter anderem in Lehrproben, einem pädagogisch-psychologischen Kolloquium sowie mündlichen Prüfungen in Fachdidaktik, Schulrecht, Schulkunde und staatsbürgerlicher Bildung nachgewiesen."},
          {title:"Phasenübergreifende Anschlusslogik",items:["wissenschaftliche Modelle situationsbezogen nutzen","Unterricht zunehmend eigenständig planen, durchführen und verantworten","Wirkungen beobachten, Feedback verarbeiten und Handlungsalternativen erproben","Subjektive Theorien unter Handlungsdruck prüfen und weiterentwickeln"]},
          {title:"Universitätsberufsschule · Transfer in die 2. Phase",text:"Die Universitätsberufsschule beteiligt sich auch am Vorbereitungsdienst. Erkenntnisse aus Forschung und universitärer Lehre werden in Module, Workshops und weitere Ausbildungsimpulse eingebracht. Erfahrungen und Fragestellungen aus Seminar- und Einsatzschule fließen umgekehrt in Forschung, Lehre und die Weiterentwicklung unserer Konzepte zurück."},
          {title:"Aktuelles und praktische Orientierung",text:"Die Startseite des Staatlichen Studienseminars bündelt aktuelle Hinweise, Termine, Modulpläne, Downloads und weitere Informationen zur Organisation des Vorbereitungsdiensts."}
        ],
        sequence:"angeleitet beobachten und erproben → beraten und reflektieren → eigenverantwortlich unterrichten → professionelle Sicherheit entwickeln",
        links:["Bachelor und Master als wissenschaftliche Grundlage","Seminar- und Einsatzschule als berufspraktische Entwicklungsräume","Universitätsberufsschule als Transfer- und Reflexionsraum","Zweite Staatsprüfung als professionsbezogener Nachweis"],
        articleLinks:[
          {label:"Staatliches Studienseminar · Startseite und aktuelle Hinweise",href:"https://studien-seminar.de/"},
          {label:"Staatliches Studienseminar · Ausbildungsziele",href:"https://studien-seminar.de/index.php/vorbereitungsdienst/inhaltliches-festlegungen/ausbildungsziele"},
          {label:"Referenzrahmen · PDF (Stand April 2025)",href:"https://studien-seminar.de/inhalte/downloads/Referenzrahmen/Referenzrahmen.pdf"},
          {label:"ZALBV § 3 · Ziel und Gliederung",href:"https://www.gesetze-bayern.de/Content/Document/BayZALBV-3"},
          {label:"ZALBV § 7 · Ausbildung an Einsatzschulen",href:"https://www.gesetze-bayern.de/Content/Document/BayZALBV-7"},
          {label:"Staatliches Studienseminar · 1. Ausbildungsjahr",href:"https://studien-seminar.de/index.php/vorbereitungsdienst/rahmenbedingungen/1-jahr-an-seminarschule"}
        ],
        sourceGroups:[
          {title:"Kompetenzrahmen · Stand April 2025",entries:["Referenzrahmen für die 2. Phase der Lehrerbildung an beruflichen Schulen in Bayern","KMK-Standards für die Lehrerbildung","DigCompEdu Bavaria"]},
          {title:"Rechtsgrundlagen · Stand 2025/2026",entries:["ZALBV §§ 3, 6 und 7","LPO II §§ 18 bis 20"]}
        ]
      }
    },
    {
      id:"fortbildung",
      index:"3. Phase · Bayern",
      title:"Fort- und Weiterbildung",
      subtitle:"Professionalisierung fortführen",
      modules:[],
      compactItems:[
        {eyebrow:"Individuell",title:"12 Tage · 4 Jahre",text:"Bedarf klären · FIBS nutzen"},
        {eyebrow:"Schulintern",title:"Mind. ⅓ SCHILF",text:"Kollegial und schulbezogen"},
        {eyebrow:"Systemisch",title:"RLFB · ALP · Weiterbildung",text:"Regional · zentral · neue Lehrbefähigung"}
      ],
      detail:{
        kicker:"3. Phase · Bayern · berufsbegleitend · lebenslange Kompetenzentwicklung",
        title:"Fort- und Weiterbildung",
        text:"Professionalisierung endet nicht mit dem Berufseinstieg. Wissen, Können und Wollen werden im rekursiven Dialog von wissenschaftlicher Theorie, Subjektiven Theorien und berufsschulischer Praxis bedarfsbezogen, kollegial und forschungsinformiert weiterentwickelt. Individuelle Entwicklung, schulische Qualitätsarbeit sowie Veränderungen von Beruf, Technik, KI und Gesellschaft werden dabei aufeinander bezogen.",
        sections:[
          {title:"Kompetenzentwicklung über die Berufslaufbahn",text:"Fort- und Weiterbildung ist damit keine Folge isolierter Veranstaltungen, sondern die dritte Phase eines fortlaufenden Professionalisierungsprozesses.",items:["berufliche Erfahrungen, Irritationen und neue Anforderungen als Entwicklungsanlässe wahrnehmen","eigene Subjektive Theorien und bisherige Handlungsroutinen sichtbar machen und prüfen","wissenschaftliche Erkenntnisse, kollegiale Perspektiven und praxisnahe Impulse erschließen","erweiterte Handlungsoptionen in Unterricht und Schule erproben und ihre Wirkungen evaluieren","fachliche, berufspädagogisch-didaktische sowie digitale und KI-bezogene Könnerschaft weiterentwickeln","Erkenntnisse in Kollegium, Schulentwicklung und professionelle Netzwerke zurückspielen"]},
          {title:"Individuelle Fortbildung",text:"In Bayern gilt die Fortbildungsverpflichtung mit zwölf Fortbildungstagen innerhalb von vier Jahren als erfüllt; ein Tag entspricht einem Richtwert von fünf Zeitstunden. Bedarf und Schwerpunkte werden mit der Schulleitung reflektiert. Angebote und Anmeldungen werden insbesondere über FIBS gebündelt."},
          {title:"Schulinterne Lehrerfortbildung · SCHILF",text:"Mindestens ein Drittel der Fortbildungsverpflichtung ist schulintern abzuleisten. SCHILF orientiert sich unmittelbar am Bedarf des Kollegiums und verbindet individuelles Lernen mit Unterrichts-, Personal- und Schulentwicklung."},
          {title:"Regional und zentral",text:"Regionale Lehrerfortbildung wird für berufliche Schulen insbesondere durch die Regierungen organisiert. Die ALP Dillingen bietet zentrale Formate für Lehrkräfte aller Schularten; Präsenz-, Online- und Blended-Learning-Angebote werden über FIBS zugänglich gemacht."},
          {title:"Weiterbildung",text:"Weiterbildung bezeichnet den berufsbegleitenden Erwerb einer weiteren Lehrbefähigung. Sie findet in der Regel an einer Universität, in Ausnahmefällen an der ALP Dillingen statt und endet üblicherweise mit einer Ersten Staatsprüfung."},
          {title:"Universitätsberufsschule · Transfer in die 3. Phase",text:"Die Universitätsberufsschule beteiligt sich auch an Fort- und Weiterbildung. Forschungserkenntnisse und erprobte Konzepte fließen in Module, Workshops, schulinterne Impulse und weitere Transferformate ein. Zugleich erzeugen Fragen aus Unterricht und Schulentwicklung neue Forschungs- und Entwicklungsaufgaben – Praxis und Theorie bleiben so auch nach dem Berufseinstieg wechselseitig verbunden."}
        ],
        sequence:"Bedarf erkennen → Fortbildung auswählen → Handeln weiterentwickeln → Wirkung prüfen → Wissen teilen → neuen Bedarf bestimmen",
        links:["Individuelle Professionalisierung","Kollegiale Unterrichtsentwicklung","Schul- und Personalentwicklung","KI-souveräne berufspädagogisch-didaktische Könnerschaft","Universitätsberufsschule als Forschungs- und Transferpartner","Berufliche und technologische Transformation"],
        articleLinks:[
          {label:"StMUK · Rechtliche Rahmenbedingungen",href:"https://www.km.bayern.de/unterrichten/fort-und-weiterbildung/rechtliche-rahmenbedindungen"},
          {label:"StMUK · Anbieter und Ebenen der Lehrerfortbildung",href:"https://www.km.bayern.de/unterrichten/fort-und-weiterbildung/anbieter-von-lehrerfortbildung"},
          {label:"FIBS · Fortbildungsportal Bayern",href:"https://fibs.alp.dillingen.de/"}
        ],
        sourceGroups:[
          {title:"Bayerischer Rahmen · Stand 2026",entries:["Art. 20 Abs. 2 BayLBG","§ 9a Abs. 2 LDO","KMBek Lehrerfortbildung in Bayern"]}
        ]
      }
    }
  ],
  competenceProfiles: {
    "begleitetes-sps-i":{contribution:"Erster systematischer Übergang von Wissen zu pädagogisch-didaktischem Können.",goals:["Unterricht und schulische Handlungssituationen systematisch und theoriegeleitet beobachten.","Beobachtung und Bewertung voneinander unterscheiden und eigene Wahrnehmungs- und Deutungsmuster reflektieren.","die zentralen Tätigkeitsfelder beruflicher Lehrkräfte in der schulischen Praxis identifizieren und analysieren.","Unterricht unter Berücksichtigung von Lernvoraussetzungen, Kompetenzzielen, Lerngegenständen und Rahmenbedingungen planen.","erste Unterrichtssequenzen bzw. Unterrichtsstunden eigenständig durchführen.","Lernprozesse beobachten und situativ angemessen auf Lernende reagieren.","die eigene Unterrichtsdurchführung anhand zuvor bestimmter Kriterien analysieren.","Rückmeldungen von Mentor:innen, Lehrkräften und Peers konstruktiv für die Weiterentwicklung des eigenen Handelns nutzen.","Theorieangebote aus Berufspädagogik und Technikdidaktik zur Interpretation konkreter Praxiserfahrungen heranziehen.","eigene subjektive Theorien über Unterricht, Lernende und die Rolle der Lehrkraft identifizieren und kritisch prüfen.","eigene Stärken, Entwicklungsbedarfe und professionelle Orientierungen einschätzen.","die eigene Eignung und Motivation für den Lehrerberuf reflektieren.","Unterrichtsbeobachtungen anhand theoriegeleiteter Beobachtungsaufträge durchführen und systematisch auswerten.","Unterrichtsentwürfe kooperativ entwickeln und begründen.","in Micro-Teaching- und Peer-Feedback-Situationen alternatives pädagogisch-didaktisches Handeln erproben.","Erfahrungen aus schulischer Praxis systematisch mit universitären Wissensbeständen rückkoppeln."]},
    "arbeitskunde":{contribution:"Grundlegung des pädagogisch-psychologischen Wissens über Lernen, Entwicklung und Interaktion als Voraussetzung professioneller Wahrnehmung und pädagogischen Handelns.",goals:["grundlegende arbeits-, lern-, motivations- und entwicklungspsychologische Konzepte beschreiben und auf berufliche Lern- und Arbeitssituationen beziehen.","Bedingungen menschlichen Lernens, der Informationsverarbeitung und des Gedächtnisses erklären und deren Bedeutung für berufliche Bildungsprozesse beurteilen.","Motivation, Volition und Emotion als Einflussgrößen beruflichen Lernens und Handelns analysieren.","entwicklungspsychologische Besonderheiten von Jugendlichen und jungen Erwachsenen in beruflichen Bildungsprozessen berücksichtigen.","Prozesse beruflicher Sozialisation, Rollenentwicklung und beruflicher Identitätsbildung erklären.","sozialpsychologische Prozesse in Lerngruppen und betrieblichen bzw. schulischen Arbeitszusammenhängen analysieren.","ausgewählte Persönlichkeitsmodelle zur Reflexion individuellen Verhaltens und der eigenen professionellen Entwicklung nutzen.","grundlegende Verfahren der Beobachtung und pädagogischen Diagnose unterscheiden und situationsangemessen einsetzen.","Belastungs-, Beanspruchungs- und Sicherheitsaspekte beruflicher Arbeit analysieren.","Kommunikation und Interaktion in beruflichen Lehr-Lern-Kontexten theoriegeleitet beschreiben und reflektieren.","eigenes Wahrnehmen, Interpretieren und Handeln gegenüber Lernenden kritisch reflektieren und die Grenzen intuitiver Personenbeurteilungen erkennen."]},
    "berufskunde":{contribution:"Aufbau eines systemischen Verständnisses beruflicher Bildung und Herstellung der Verbindung zwischen Beruf, Berufsbildungssystem und berufsschulischem Bildungsauftrag.",goals:["historische Entwicklungslinien der beruflichen Bildung in Deutschland beschreiben und zur gegenwärtigen Struktur des Berufsbildungssystems in Beziehung setzen.","zentrale Institutionen, Akteure, Rechtsgrundlagen und Steuerungsmechanismen der beruflichen Bildung erklären.","die Funktionen und das Zusammenwirken der Lernorte im dualen System analysieren.","Ausbildungsordnungen, Rahmenlehrpläne und weitere curriculare Ordnungsmittel erschließen und zueinander in Beziehung setzen.","die Lernfeldkonzeption als curriculares Strukturprinzip beruflicher Bildung erklären.","berufliche Tätigkeiten, Berufsprofile und Arbeitsprozesse als Ausgangspunkte beruflicher Bildungsprozesse analysieren.","Veränderungen beruflicher Arbeit durch technologische, gesellschaftliche und organisationale Entwicklungen erkennen und hinsichtlich ihrer Bedeutung für Berufsbildung beurteilen.","die spezifische Bildungsfunktion der Berufsschule im Verhältnis zu betrieblicher Ausbildung und Beschäftigungssystem bestimmen.","Spannungsverhältnisse zwischen Bildungsauftrag, Beschäftigungsfähigkeit, betrieblicher Verwertbarkeit und Persönlichkeitsentwicklung reflektieren.","die eigene zukünftige Tätigkeit als Lehrkraft innerhalb des institutionellen und gesellschaftlichen Systems beruflicher Bildung verorten."]},
    "berufspaedagogik-i":{contribution:"Übergang vom Verständnis beruflicher Bildung zur begründeten Planung berufsschulischer Lehr-Lern-Prozesse.",goals:["zentrale Grundbegriffe und theoretische Positionen der Berufspädagogik erläutern.","den Bildungs- und Erziehungsauftrag beruflicher Schulen begründen und auf konkrete schulische Handlungssituationen beziehen.","Kompetenzorientierung als Leitidee beruflicher Bildung erläutern und von einer bloßen Orientierung an beobachtbarer Performanz unterscheiden.","berufliche Handlungskompetenz als Ziel beruflicher Bildungsprozesse theoretisch einordnen.","lernfeldstrukturierte Lehrpläne analysieren und daraus Anforderungen an die Unterrichtsplanung ableiten.","berufliche Situationen und berufliche Handlungen hinsichtlich ihres Bildungspotenzials analysieren.","grundlegende Prinzipien der Planung beruflicher Lehr-Lern-Prozesse anwenden.","Lernziele bzw. Kompetenzziele begründet formulieren und mit Lerngegenständen, Lernhandlungen und Unterrichtsmethoden abstimmen.","einfache berufliche Lehr-Lern-Arrangements planen und hinsichtlich ihrer Kompetenzorientierung beurteilen.","Unterrichtsverläufe theoriegeleitet analysieren und reflektieren.","die eigene Rolle als Lehrkraft im Spannungsfeld von Unterrichten, Erziehen und beruflicher Kompetenzentwicklung reflektieren."]},
    "technikdidaktik-grundlagen":{contribution:"Aufbau der Fähigkeit, berufliche und technische Gegenstände in strukturierte Lernprozesse zu transformieren.",goals:["Gegenstand, Aufgaben und zentrale Positionen der Didaktik technischer beruflicher Bildung erläutern.","technische Arbeits- und Geschäftsprozesse hinsichtlich ihrer fachlichen, beruflichen und didaktischen Struktur analysieren.","aus beruflichen Situationen relevante Lerngegenstände und Kompetenzanforderungen erschließen.","Lernfelder und Lernsituationen didaktisch analysieren und für die Unterrichtsplanung operationalisieren.","Situationshandlung und Lernhandlung unterscheiden und systematisch miteinander verschränken.","technische Lerngegenstände hinsichtlich ihrer fachsystematischen und handlungssystematischen Struktur analysieren.","berufliche Problemstellungen in lernförderliche Aufgabenstellungen überführen.","geeignete Methoden, Medien und Repräsentationsformen für technische Lehr-Lern-Prozesse begründet auswählen.","Diagnose, Lernbegleitung, Feedback und Leistungsbewertung als unterschiedliche didaktische Funktionen unterscheiden und aufeinander abstimmen.","Anforderungen an Sicherheit, Normen und fachgerechtes technisches Handeln in Unterrichtsprozesse integrieren.","eigene Unterrichtsplanungen anhand technikdidaktischer Kriterien analysieren und weiterentwickeln."]},
    "technikdidaktik-grundlagen-option-2":{contribution:"Aufbau der Fähigkeit, berufliche und technische Gegenstände in strukturierte Lernprozesse zu transformieren.",goals:["Gegenstand, Aufgaben und zentrale Positionen der Didaktik technischer beruflicher Bildung erläutern.","technische Arbeits- und Geschäftsprozesse hinsichtlich ihrer fachlichen, beruflichen und didaktischen Struktur analysieren.","aus beruflichen Situationen relevante Lerngegenstände und Kompetenzanforderungen erschließen.","Lernfelder und Lernsituationen didaktisch analysieren und für die Unterrichtsplanung operationalisieren.","Situationshandlung und Lernhandlung unterscheiden und systematisch miteinander verschränken.","technische Lerngegenstände hinsichtlich ihrer fachsystematischen und handlungssystematischen Struktur analysieren.","berufliche Problemstellungen in lernförderliche Aufgabenstellungen überführen.","geeignete Methoden, Medien und Repräsentationsformen für technische Lehr-Lern-Prozesse begründet auswählen.","Diagnose, Lernbegleitung, Feedback und Leistungsbewertung als unterschiedliche didaktische Funktionen unterscheiden und aufeinander abstimmen.","Anforderungen an Sicherheit, Normen und fachgerechtes technisches Handeln in Unterrichtsprozesse integrieren.","eigene Unterrichtsplanungen anhand technikdidaktischer Kriterien analysieren und weiterentwickeln."]},
    "sps-i":{contribution:"Erster systematischer Übergang von Wissen zu pädagogisch-didaktischem Können.",goals:["Unterricht und schulische Handlungssituationen systematisch und theoriegeleitet beobachten.","Beobachtung und Bewertung voneinander unterscheiden und eigene Wahrnehmungs- und Deutungsmuster reflektieren.","die zentralen Tätigkeitsfelder beruflicher Lehrkräfte in der schulischen Praxis identifizieren und analysieren.","Unterricht unter Berücksichtigung von Lernvoraussetzungen, Kompetenzzielen, Lerngegenständen und Rahmenbedingungen planen.","erste Unterrichtssequenzen bzw. Unterrichtsstunden eigenständig durchführen.","Lernprozesse beobachten und situativ angemessen auf Lernende reagieren.","die eigene Unterrichtsdurchführung anhand zuvor bestimmter Kriterien analysieren.","Rückmeldungen von Mentor:innen, Lehrkräften und Peers konstruktiv für die Weiterentwicklung des eigenen Handelns nutzen.","Theorieangebote aus Berufspädagogik und Technikdidaktik zur Interpretation konkreter Praxiserfahrungen heranziehen.","eigene subjektive Theorien über Unterricht, Lernende und die Rolle der Lehrkraft identifizieren und kritisch prüfen.","eigene Stärken, Entwicklungsbedarfe und professionelle Orientierungen einschätzen.","die eigene Eignung und Motivation für den Lehrerberuf reflektieren."]},
    "digitalisierung":{contribution:"Erweiterung berufspädagogisch-didaktischer Könnerschaft um die Fähigkeit, digitale und KI-induzierte Transformation fachlich und didaktisch zu gestalten.",goals:["Digitalisierung als technologischen, arbeitsorganisatorischen und gesellschaftlichen Transformationsprozess beruflicher Arbeit analysieren.","Auswirkungen digitaler Technologien auf Berufe, Tätigkeitsprofile und Kompetenzanforderungen beurteilen.","digitale Medien und Technologien hinsichtlich ihres didaktischen Potenzials analysieren.","digitale Lehr-Lern-Arrangements kompetenzorientiert planen, entwickeln und evaluieren.","digitale Werkzeuge begründet in berufliche Lernprozesse integrieren.","Möglichkeiten und Grenzen KI-basierter Systeme für berufliches Lernen und Lehren beurteilen.","KI-Systeme für Planung, Lernbegleitung, Differenzierung, Feedback und weitere professionelle Aufgaben reflektiert einsetzen.","Veränderungen von Wissen, Können und beruflicher Handlungskompetenz unter Bedingungen von Digitalisierung und KI analysieren.","Datenschutz, Urheberrecht, algorithmische Verzerrungen, Transparenz und weitere ethische bzw. rechtliche Fragen berücksichtigen.","eigene digitale und KI-bezogene Handlungskompetenz kritisch einschätzen und weiterentwickeln.","Digitalisierung nicht lediglich als Medieneinsatz, sondern als Gegenstand beruflicher Bildungsprozesse verstehen und gestalten."]},
    "forschungsseminar-ba":{contribution:"Übergang von der Rezeption berufspädagogisch-didaktischer Forschung zur eigenständigen wissenschaftlichen Bearbeitung beruflicher Bildungsprobleme.",goals:["berufspädagogische und technikdidaktische Problemstellungen in wissenschaftlich bearbeitbare Fragestellungen überführen.","den Forschungsstand zu einer Fragestellung systematisch erschließen und kritisch einordnen.","theoretische Bezugssysteme auswählen und zur Präzisierung einer Forschungsfrage nutzen.","Forschungsfragen, theoretischen Rahmen und methodisches Vorgehen konsistent aufeinander beziehen.","grundlegende qualitative und quantitative Forschungsdesigns hinsichtlich ihrer Eignung beurteilen.","geeignete Verfahren der Datenerhebung und -auswertung begründet auswählen.","Gütekriterien wissenschaftlicher Forschung auf eigene Forschungsvorhaben anwenden.","ein eigenes Forschungsdesign entwickeln und argumentativ verteidigen.","wissenschaftliche Ergebnisse kritisch interpretieren und Grenzen der Aussagekraft bestimmen.","Forschungsprozesse unter forschungsethischen Gesichtspunkten reflektieren.","ein Bachelorarbeitsvorhaben selbstständig strukturieren und wissenschaftlich bearbeiten."]},
    "berufspaedagogik-ii":{contribution:"Vertiefung von pädagogischem Wissen und Reflexionsfähigkeit hin zu begründetem professionellem Entscheiden unter komplexen Bedingungen.",goals:["zentrale berufspädagogische Theorien und Forschungsansätze vertieft analysieren und kritisch vergleichen.","komplexe berufliche Bildungsprozesse auf individueller, institutioneller und gesellschaftlicher Ebene analysieren.","Heterogenität und unterschiedliche Lernvoraussetzungen in beruflichen Bildungsprozessen diagnostisch erfassen und theoretisch einordnen.","pädagogische Handlungsoptionen für komplexe Unterrichts-, Beratungs- und Erziehungssituationen entwickeln.","Spannungsverhältnisse professionellen Lehrerhandelns identifizieren und begründete Entscheidungen treffen.","wissenschaftliche Erkenntnisse zur Analyse konkreter schulischer Problemstellungen heranziehen.","unterschiedliche Perspektiven auf berufliche Bildung gegeneinander abwägen und eigene Positionen argumentativ begründen.","die eigene professionelle Entwicklung und eigene subjektive Theorien kritisch reflektieren.","pädagogisches Handeln nicht ausschließlich situativ-pragmatisch, sondern theorie- und evidenzbasiert begründen.","Verantwortung für individuelle Bildungsprozesse und die Entwicklung beruflicher Schulen reflektiert übernehmen."]},
    "sps-ii":{contribution:"Weiterentwicklung von ersten Handlungserfahrungen zu zunehmend selbstständigem, adaptivem und begründbarem professionellem Können.",goals:["komplexere Unterrichtseinheiten zunehmend selbstständig planen, durchführen und evaluieren.","Lernvoraussetzungen systematisch erfassen und bei der Unterrichtsplanung berücksichtigen.","berufliche Lernsituationen adressatengerecht und kompetenzorientiert gestalten.","fachliche, berufliche und didaktische Anforderungen in Unterrichtsentscheidungen integrieren.","Lernprozesse adaptiv begleiten und Unterrichtshandeln situativ anpassen.","unterschiedliche Formen von Diagnose, Feedback und Leistungsbewertung lernförderlich einsetzen.","Unterrichtsstörungen und pädagogisch anspruchsvolle Situationen professionell bearbeiten.","eigene Entscheidungen im Unterricht theoriegeleitet begründen.","Unterrichtsdaten, Beobachtungen und Feedback systematisch zur Evaluation eigenen Handelns nutzen.","Routinen entwickeln, ohne professionelles Handeln auf schematische Abläufe zu reduzieren.","eigenes Unterrichtshandeln hinsichtlich seiner Wirkungen kritisch analysieren.","Verantwortung für längerfristige Lern- und Kompetenzentwicklungsprozesse übernehmen."]},
    "qualitaet-team":{contribution:"Erweiterung der professionellen Perspektive vom eigenen Unterricht auf Team, Organisation und systemische Schulentwicklung.",goals:["Schule als Organisation und als lernendes Handlungssystem analysieren.","grundlegende Ansätze der Schul-, Organisations-, Personal- und Qualitätsentwicklung erläutern.","schulische Entwicklungsprozesse anhand geeigneter Modelle analysieren.","Daten und Evaluationsergebnisse zur Identifikation schulischer Entwicklungsbedarfe nutzen.","Qualitätsentwicklungsmaßnahmen systematisch planen, durchführen und evaluieren.","Prozesse professioneller Kooperation und Teamarbeit analysieren und gestalten.","unterschiedliche Rollen, Interessen und Perspektiven schulischer Akteure berücksichtigen.","Besprechungs-, Kooperations- und Entwicklungsprozesse zielorientiert moderieren.","Konflikte und Widerstände in Veränderungsprozessen analysieren und konstruktiv bearbeiten.","technologische und gesellschaftliche Veränderungen als Anlässe schulischer Organisationsentwicklung begreifen.","die eigene Rolle nicht auf Unterricht beschränken, sondern als Mitverantwortung für die Entwicklung der Schule verstehen.","Bereitschaft zur Kooperation, Innovation und gemeinsamen Verantwortungsübernahme entwickeln und reflektieren."]},
    "technikdidaktik-i":{contribution:"Vertiefung technikdidaktischer Analyse- und Transformationskompetenz für komplexe technische Lerngegenstände.",goals:["zentrale technikdidaktische Theorien und Modelle systematisch einordnen und kritisch vergleichen.","komplexe technische Arbeits- und Geschäftsprozesse fachlich und didaktisch analysieren.","berufliche Handlungssituationen hinsichtlich ihrer fachlichen Struktur und ihres Bildungspotenzials untersuchen.","fachsystematische und handlungssystematische Zugänge zu technischen Lerngegenständen aufeinander beziehen.","technische Inhalte didaktisch reduzieren bzw. rekonstruieren, ohne ihre fachliche Struktur unzulässig zu verfälschen.","anspruchsvolle Lernsituationen aus beruflichen Arbeitsprozessen entwickeln.","Situationshandlungen und Lernhandlungen gezielt miteinander verschränken.","unterschiedliche Repräsentationsformen technischer Systeme und Prozesse lernförderlich einsetzen.","typische fachliche Fehlvorstellungen und Lernschwierigkeiten analysieren.","technikdidaktische Entscheidungen theoriegeleitet begründen und kritisch reflektieren."]},
    "technikdidaktik-ii":{contribution:"Übergang von angeleiteter technikdidaktischer Gestaltung zu eigenständiger, begründeter und innovationsfähiger technikdidaktischer Könnerschaft.",goals:["komplexe und offene technische Lehr-Lern-Arrangements eigenständig entwickeln.","technische Lernprozesse unter Berücksichtigung unterschiedlicher Kompetenzniveaus adaptiv gestalten.","anspruchsvolle berufliche Problemstellungen als Ausgangspunkt längerfristiger Kompetenzentwicklungsprozesse nutzen.","fachpraktisches, fachtheoretisches und reflexives Lernen systematisch miteinander verbinden.","Diagnoseverfahren zur Analyse technischer Kompetenzentwicklung auswählen und entwickeln.","kompetenzorientierte Formen der Leistungsfeststellung und -bewertung gestalten.","digitale und KI-basierte Technologien fachdidaktisch begründet in technische Lernprozesse integrieren.","Auswirkungen technologischer Innovationen auf technische Berufe analysieren und daraus curriculare Konsequenzen ableiten.","bestehende Lernsituationen und Unterrichtskonzepte anhand technikdidaktischer Kriterien evaluieren und weiterentwickeln.","eigene technikdidaktische Konzeptionen theoretisch begründen und gegenüber Alternativen argumentativ vertreten.","die eigene beruflich-fachliche und technikdidaktische Kompetenz als dauerhaft entwicklungsbedürftigen Bestandteil professioneller Könnerschaft reflektieren."]},
    "forschungsseminar-ma":{contribution:"Entwicklung von angeleiteter Forschungskompetenz im Bachelor hin zur weitgehend selbstständigen Produktion berufspädagogisch-didaktischer wissenschaftlicher Erkenntnisse.",goals:["komplexe berufspädagogische oder technikdidaktische Forschungsprobleme identifizieren und theoretisch präzisieren.","Forschungsstände systematisch erschließen, strukturieren und Forschungslücken begründet bestimmen.","eigenständige und wissenschaftlich relevante Forschungsfragen bzw. Hypothesen entwickeln.","theoretische Modelle für eigene Untersuchungen operationalisieren bzw. als analytischen Bezugsrahmen verwenden.","anspruchsvollere qualitative, quantitative oder Mixed-Methods-Designs hinsichtlich ihrer Erkenntnismöglichkeiten und Grenzen beurteilen.","ein zur Forschungsfrage passendes Untersuchungsdesign eigenständig entwickeln.","Erhebungsinstrumente auswählen, adaptieren oder selbst entwickeln und deren Qualität beurteilen.","empirische Daten methodisch kontrolliert auswerten und Ergebnisse theoriebezogen interpretieren.","alternative Interpretationen und Limitationen eigener Ergebnisse systematisch diskutieren.","Gütekriterien und forschungsethische Anforderungen eigenständig auf den gesamten Forschungsprozess anwenden.","wissenschaftliche Argumentationen kohärent entwickeln und Forschungsergebnisse adressatengerecht präsentieren und verteidigen.","ein Masterarbeitsprojekt weitgehend selbstständig konzipieren, durchführen und kritisch reflektieren."]}
  },
  bachelorDetails: {
    "arbeitskunde":{
      contribution:"Entwicklung eines Verständnisses arbeits-, berufs- und entwicklungspsychologischer Grundlagen beruflicher Entwicklungsprozesse.",
      contents:["Grundlagen der Arbeits-, Berufs- und Organisationspsychologie","Berufliche Sozialisation und Identitätsentwicklung","Entwicklungspsychologische Grundlagen des Jugend- und jungen Erwachsenenalters","Motivation, Selbstwirksamkeit und berufliche Kompetenzentwicklung","Personale und soziale Kompetenzen im beruflichen Kontext","Kommunikation, Kooperation und Gruppenprozesse","Rollenverständnis und professionelle Beziehungen in der beruflichen Bildung"],
      qualification:["Die Studierenden verfügen über grundlegende Kenntnisse arbeits-, berufs- und entwicklungspsychologischer Konzepte und Modelle sowie deren Bedeutung für berufliche Bildungs- und Sozialisationsprozesse. Sie können Zusammenhänge zwischen Arbeit, beruflicher Entwicklung, Persönlichkeit, Motivation und Kompetenzentwicklung erläutern und deren Relevanz für das Lernen und Arbeiten in der beruflichen Bildung begründen.","Sie sind in der Lage, individuelle Entwicklungs- und Sozialisationsprozesse sowie psychologische und soziale Einflussfaktoren auf das Lernen, die Motivation und die Zusammenarbeit von Auszubildenden zu analysieren und hinsichtlich ihrer Bedeutung für berufliche Bildungsprozesse einzuordnen. Darüber hinaus können sie Grundlagen der Arbeits- und Berufspsychologie auf ausgewählte berufspädagogische Fragestellungen übertragen und zur Analyse beruflicher Handlungssituationen heranziehen.","Die Studierenden reflektieren ihre eigene berufliche Rolle sowie personale und soziale Voraussetzungen professionellen Handelns. Sie entwickeln ein Verständnis für die Bedeutung von Kommunikation, Kooperation und professioneller Beziehungsgestaltung im Umgang mit Lernenden und leiten daraus grundlegende Anforderungen an ihr zukünftiges Handeln als Lehrkraft an beruflichen Schulen ab."]
    },
    "berufskunde":{
      contribution:"Entwicklung eines Verständnisses des Berufsbildungssystems sowie beruflicher Handlungsfelder als Gegenstand der Beruflichen Bildung.",
      contents:["Schularten des berufsbildenden Schulwesens","Rahmenlehrpläne und Ausbildungsordnungen","Akteure, Institutionen und Lernorte der beruflichen Bildung","Rechtliche Grundlagen der Berufsbildung (insbesondere BBiG, HwO)","Berufsbilder, berufliche Handlungsfelder und berufliche Anforderungen","Wandel von Arbeit und Beruf im Kontext technologischer, wirtschaftlicher und gesellschaftlicher Entwicklungen","Anforderungen und Kompetenzprofile in technischen Berufen","Aktuelle Herausforderungen der Berufsbildung (z. B. Digitalisierung, Künstliche Intelligenz, Nachhaltigkeit, Fachkräftesicherung)","Ausbildungsverträge und Prüfungswesen zuständiger Stellen"],
      qualification:["Die Studierenden verfügen über grundlegende Kenntnisse der Strukturen, Akteure und rechtlichen Rahmenbedingungen des deutschen Berufsbildungssystems. Sie können die Bedeutung unterschiedlicher Lernorte, Institutionen und Ordnungsmittel für die Gestaltung beruflicher Bildungsprozesse erläutern und deren Zusammenwirken im System der dualen Berufsausbildung einordnen.","Sie sind in der Lage, Berufsbilder, berufliche Handlungsfelder sowie berufliche Anforderungen technischer Ausbildungsberufe zu analysieren und den Einfluss technologischer, wirtschaftlicher und gesellschaftlicher Transformationsprozesse auf die Berufe, Arbeitsprozesse und Kompetenzanforderungen zu beurteilen. Dabei können sie Entwicklungen der Arbeitswelt hinsichtlich ihrer Konsequenzen für die berufliche Bildung reflektieren und begründet einordnen.","Die Studierenden entwickeln ein Verständnis für den Zusammenhang von Beruf, Arbeit und Beruflicher Bildung als Grundlage professionellen Handelns als Lehrkraft. Sie erkennen die Notwendigkeit einer kontinuierlichen Auseinandersetzung mit der Entwicklung von Berufen, Arbeitsprozessen und Kompetenzanforderungen und reflektieren deren Bedeutung für die Gestaltung beruflicher Bildungs- und Lernprozesse."]
    },
    "berufspaedagogik-i":{
      contribution:"Entwicklung eines grundlegenden Verständnisses beruflicher Bildung und professionellen Lehrerhandelns.",
      contents:["Bildungs- und Erziehungsauftrag beruflicher Schulen","Berufliche Bildung im Spannungsfeld von Individuum, Beruf, Gesellschaft und Arbeitswelt","Grundlagen beruflicher Kompetenzentwicklung","Professionalisierung und professionelles Handeln von Lehrkräften an beruflichen Schulen","Berufspädagogische und allgemeindidaktische Theorien und Modelle","Reflexion der professionellen Rolle und des beruflichen Selbstverständnisses als Lehrkraft","Aktuelle Herausforderungen beruflicher Bildung (z. B. Digitalisierung, Künstliche Intelligenz, Nachhaltigkeit, Heterogenität)"],
      qualification:["Die Studierenden verfügen über grundlegende Kenntnisse zentraler Begriffe, Theorien, Modelle und Zielsetzungen der Berufspädagogik. Sie können den Bildungs- und Erziehungsauftrag beruflicher Schulen erläutern sowie die Bedeutung beruflicher Bildung für Individuum, Beruf, Gesellschaft und Arbeitswelt begründen.","Sie sind in der Lage, berufspädagogische Fragestellungen unter Rückgriff auf wissenschaftliche Erkenntnisse und Theorien zu analysieren, unterschiedliche berufspädagogische Positionen einzuordnen und deren Bedeutung für die Gestaltung beruflicher Bildungsprozesse kritisch zu reflektieren. Darüber hinaus können sie aktuelle Entwicklungen und Transformationsprozesse wie beispielsweise im Zusammenhang mit Digitalisierung, Künstlicher Intelligenz, Nachhaltigkeit oder gesellschaftlichem Wandel hinsichtlich ihrer Bedeutung für die Berufliche Bildung beurteilen.","Die Studierenden entwickeln ein grundlegendes Verständnis professionellen Handelns von Lehrkräften an beruflichen Schulen. Sie reflektieren die Anforderungen an professionelles pädagogisches Handeln sowie ihre eigene Rolle als angehende Lehrkraft und entwickeln ein wissenschaftlich fundiertes berufliches Selbstverständnis als Grundlage für die weitere pädagogisch-didaktische, schulpraktische und wissenschaftliche Professionalisierung."]
    },
    "technikdidaktik-grundlagen":{
      contribution:"Entwicklung eines grundlegenden Verständnisses zur Analyse, Planung und Umsetzung beruflicher Lehr-Lern-Prozesse.",
      contents:["Grundlagen der Technikdidaktik","Technikdidaktische Theorien und Modelle","Lernfeldkonzept und Gestaltung kompetenzorientierter Lernsituationen","Analyse beruflicher Anforderungssituationen als didaktischer Ausgangspunkt","Planung und Entwicklung beruflicher Lehr-Lern-Prozesse","Grundlagen der Lernprozessbegleitung sowie des Feedbacks und der Leistungsbewertung","Reflexion und Evaluation beruflicher Lehr-Lern-Prozesse","Theoriegeleitete Vorbereitung und Reflexion der begleiteten Schulpraktischen Studien"],
      qualification:["Die Studierenden verfügen über grundlegende Kenntnisse zentraler Modelle, Konzepte und Prinzipien der Technikdidaktik sowie der Gestaltung beruflicher Lehr-Lern-Prozesse. Sie können berufliche Arbeits- und Handlungssituationen analysieren, deren didaktische Relevanz begründen und grundlegende Prinzipien systematisch kompetenzorientierter Unterrichtsgestaltung erläutern.","Sie sind in der Lage, erste berufliche Lehr-Lern-Prozesse theoriegeleitet zu planen, zu entwickeln und hinsichtlich ihrer didaktischen Qualität zu analysieren. Dabei können sie didaktische Entscheidungen unter Berücksichtigung curricularer Vorgaben, beruflicher Handlungssituationen sowie lernförderlicher Gestaltungsprinzipien begründet treffen und reflektieren. Darüber hinaus können sie grundlegende Formen der Lernprozessbegleitung, des Feedbacks und der Leistungsbewertung zielgerichtet in die Planung beruflicher Lehr-Lern-Prozesse einbeziehen.","Die Studierenden entwickeln ein grundlegendes Verständnis professioneller Unterrichtsgestaltung und erkennen die Bedeutung einer wissenschaftlich fundierten Planung, Durchführung, Reflexion und Evaluation beruflicher Lehr-Lern-Prozesse für professionelles Lehrerhandeln. Sie sind darauf vorbereitet, die erworbenen didaktischen Kenntnisse in den begleiteten Schulpraktischen Studien anzuwenden, weiterzuentwickeln und kritisch zu reflektieren."]
    },
    "technikdidaktik-grundlagen-option-2":{ref:"technikdidaktik-grundlagen"},
    "sps-i":{
      contribution:"Entwicklung erster professioneller Handlungskompetenz durch angeleitete schulische Praxiserfahrungen.",
      contents:["Kennenlernen der Aufgaben und Tätigkeitsfelder von Lehrkräften an beruflichen Schulen (Unterrichten, Erziehen, Beraten, Bewerten, Kooperieren, Innovieren)","Planung, Durchführung und Reflexion erster eigener Unterrichtsstunden","Bearbeitung berufspädagogischer und fachdidaktischer Erkundungs- und Reflexionsaufträge","Reflexion der eigenen Eignung, Motivation und professionellen Rolle als angehende Lehrkraft"],
      qualification:["Die Studierenden gewinnen einen wissenschaftlich fundierten Einblick in das Berufsfeld beruflicher Schulen und lernen die vielfältigen Aufgaben und Tätigkeitsfelder von Lehrkräften in den Bereichen Unterrichten, Erziehen, Beraten, Bewerten, Kooperieren und Innovieren kennen. Sie sind in der Lage, Unterricht sowie schulische Bildungsprozesse anhand grundlegender berufspädagogischer und fachdidaktischer Kriterien theoriegeleitet zu beobachten, zu analysieren und zu reflektieren.","Die Studierenden wenden grundlegende Erkenntnisse der Berufspädagogik und Technikdidaktik auf schulische Lehr-Lern-Situationen an. Sie planen, erproben und reflektieren erste Unterrichtsstunden unter Anleitung und beziehen dabei wissenschaftliche Erkenntnisse in ihr unterrichtliches Handeln ein.","Darüber hinaus bearbeiten sie berufspädagogische und fachdidaktische Erkundungs- und Reflexionsaufträge eigenständig, dokumentieren ihre Erfahrungen systematisch und werten diese wissenschaftlich fundiert aus.","Die Studierenden reflektieren ihre Motivation, ihre Eignung sowie ihre professionelle Rolle als angehende Lehrkraft an beruflichen Schulen. Sie entwickeln ein realistisches Verständnis der Anforderungen des Lehrerberufs und leiten daraus Konsequenzen für ihre weitere pädagogische, fachdidaktische und persönliche Professionalisierung ab."]
    },
    "begleitetes-sps-i":{
      contribution:"Entwicklung erster professioneller Handlungskompetenz durch die intensive theoriegeleitete Verzahnung von Hochschullehre und schulischer Praxis.",
      contents:["Kennenlernen der Aufgaben und Tätigkeitsfelder von Lehrkräften an beruflichen Schulen (Unterrichten, Erziehen, Beraten, Bewerten, Kooperieren, Innovieren)","Planung, Durchführung und Reflexion erster eigener Unterrichtsstunden","Bearbeitung berufspädagogischer und fachdidaktischer Erkundungs- und Reflexionsaufträge","Reflexion der eigenen Eignung, Motivation und professionellen Rolle als angehende Lehrkraft","Kontinuierliche theoriegeleitete Begleitung sowie kollegiale und individuelle Reflexion der schulpraktischen Erfahrungen samt Feedback"],
      qualification:["Die Studierenden gewinnen einen wissenschaftlich fundierten Einblick in das Berufsfeld beruflicher Schulen und lernen die vielfältigen Aufgaben und Tätigkeitsfelder von Lehrkräften in den Bereichen Unterrichten, Erziehen, Beraten, Bewerten, Kooperieren und Innovieren kennen. Sie sind in der Lage, Unterricht sowie schulische Bildungsprozesse anhand grundlegender berufspädagogischer und fachdidaktischer Kriterien theoriegeleitet zu beobachten, zu analysieren und zu reflektieren.","Die Studierenden wenden grundlegende Erkenntnisse der Berufspädagogik und Technikdidaktik kontinuierlich auf schulische Lehr-Lern-Situationen an. Sie planen, erproben und reflektieren erste Unterrichtsstunden unter intensiver fachlicher Begleitung und nutzen regelmäßige Feedback- und Reflexionsprozesse zur Weiterentwicklung ihrer didaktischen und pädagogischen Handlungskompetenz.","Darüber hinaus bearbeiten sie berufspädagogische und fachdidaktische Erkundungs- und Reflexionsaufträge eigenständig, dokumentieren ihre Erfahrungen systematisch und werten diese wissenschaftlich fundiert aus. Außerdem beziehen sie die Ergebnisse systematisch in die Weiterentwicklung ihres professionellen Handelns ein.","Die Studierenden reflektieren ihre Motivation, ihre Eignung sowie ihre professionelle Rolle als angehende Lehrkraft an beruflichen Schulen. Sie entwickeln ein realistisches Verständnis der Anforderungen des Lehrerberufs und nutzen die kontinuierliche theoriegeleitete Begleitung, um ihre pädagogische, fachdidaktische und persönliche Professionalisierung gezielt weiterzuentwickeln."]
    },
    "digitalisierung":{
      contribution:"Erweiterung berufspädagogisch-didaktischer Könnerschaft um die Fähigkeit, digitale und KI-induzierte Transformation fachlich und didaktisch zu gestalten.",
      contents:["Digitalisierung als Transformation beruflicher Arbeit und beruflicher Bildung","Auswirkungen digitaler Technologien auf Berufe, Tätigkeitsprofile und Kompetenzanforderungen","Didaktische Potenziale digitaler Medien und Technologien","Planung und Evaluation digitaler Lehr-Lern-Arrangements","Einsatzmöglichkeiten und Grenzen KI-basierter Systeme","Datenschutz, Urheberrecht, Transparenz, algorithmische Verzerrungen sowie ethische und rechtliche Fragen","Reflexion und Weiterentwicklung der eigenen digitalen und KI-bezogenen Handlungskompetenz"],
      qualification:["Die Studierenden können Digitalisierung als technologischen, arbeitsorganisatorischen und gesellschaftlichen Transformationsprozess beruflicher Arbeit analysieren und Auswirkungen digitaler Technologien auf Berufe, Tätigkeitsprofile und Kompetenzanforderungen beurteilen.","Sie sind in der Lage, digitale Medien, Werkzeuge und KI-basierte Systeme hinsichtlich ihres didaktischen Potenzials und ihrer Grenzen zu beurteilen sowie digitale Lehr-Lern-Arrangements kompetenzorientiert zu planen, zu entwickeln und zu evaluieren. Dabei berücksichtigen sie Datenschutz, Urheberrecht, algorithmische Verzerrungen, Transparenz und weitere ethische beziehungsweise rechtliche Anforderungen.","Die Studierenden reflektieren und entwickeln ihre eigene digitale und KI-bezogene Handlungskompetenz weiter. Sie verstehen Digitalisierung nicht lediglich als Medieneinsatz, sondern als Gegenstand beruflicher Bildungsprozesse, den sie fachlich und didaktisch verantwortlich gestalten."]
    },
    "forschungsseminar-ba":{
      contribution:"Übergang von der Rezeption berufspädagogisch-didaktischer Forschung zur eigenständigen wissenschaftlichen Bearbeitung beruflicher Bildungsprobleme.",
      contents:["Entwicklung wissenschaftlich bearbeitbarer berufspädagogischer und technikdidaktischer Fragestellungen","Systematische Erschließung und kritische Einordnung des Forschungsstands","Theoretische Bezugssysteme und Präzisierung von Forschungsfragen","Grundlegende qualitative und quantitative Forschungsdesigns","Verfahren der Datenerhebung und -auswertung","Gütekriterien und Forschungsethik","Entwicklung und Begründung eines eigenen Forschungsdesigns","Strukturierung eines Bachelorarbeitsvorhabens"],
      qualification:["Die Studierenden können berufspädagogische und technikdidaktische Problemstellungen in wissenschaftlich bearbeitbare Fragestellungen überführen, den Forschungsstand systematisch erschließen und theoretische Bezugssysteme zur Präzisierung einer Forschungsfrage nutzen.","Sie sind in der Lage, Forschungsfrage, theoretischen Rahmen und methodisches Vorgehen konsistent aufeinander zu beziehen. Sie beurteilen grundlegende qualitative und quantitative Forschungsdesigns, wählen geeignete Verfahren der Datenerhebung und -auswertung begründet aus und wenden Gütekriterien sowie forschungsethische Anforderungen auf eigene Vorhaben an.","Die Studierenden können ein eigenes Forschungsdesign entwickeln und argumentativ vertreten, wissenschaftliche Ergebnisse kritisch interpretieren und Grenzen ihrer Aussagekraft bestimmen. Auf dieser Grundlage strukturieren und bearbeiten sie ein Bachelorarbeitsvorhaben selbstständig."]
    }
  },
  masterDetails: {
    "berufspaedagogik-ii":{
      contribution:"Vertiefung berufspädagogischer Analyse-, Urteils-, Entscheidungs- und Reflexionsfähigkeit für professionelles Handeln in komplexen beruflichen Bildungsprozessen.",
      contents:["Professionelles Handeln von Lehrkräften in komplexen pädagogischen Situationen","Heterogenität, Individualisierung und Inklusion in der beruflichen Bildung","Diagnose individueller Lernvoraussetzungen und beruflicher Entwicklungsprozesse","Beratung, Erziehung und professionelle Beziehungsgestaltung","Umgang mit pädagogischen Spannungsfeldern, Konflikten und herausfordernden Situationen","Professionelle Urteils- und Entscheidungsprozesse unter Bedingungen von Komplexität und Unsicherheit","Reflexion subjektiver Theorien und professioneller Überzeugungen","Aktuelle Forschungsbefunde und Herausforderungen beruflicher Bildung"],
      qualification:["Die Studierenden verfügen über vertiefte Kenntnisse berufspädagogischer Theorien, Modelle und Forschungsbefunde und können diese zur Analyse komplexer beruflicher Bildungs- und Entwicklungsprozesse heranziehen. Sie können individuelle, soziale und institutionelle Bedingungen beruflichen Lernens analysieren und deren Zusammenwirken bei der Entstehung pädagogischer Handlungssituationen beurteilen.","Sie sind in der Lage, komplexe und mehrdeutige pädagogische Situationen unter Berücksichtigung unterschiedlicher Lernvoraussetzungen, professioneller Anforderungen und institutioneller Rahmenbedingungen theoriegeleitet zu analysieren, alternative Handlungsmöglichkeiten gegeneinander abzuwägen und begründete professionelle Entscheidungen zu treffen. Dabei können sie wissenschaftliche Erkenntnisse mit konkreten Anforderungen berufsschulischer Praxis in Beziehung setzen und die Reichweite sowie Grenzen unterschiedlicher Handlungsoptionen reflektieren.","Die Studierenden reflektieren eigene Überzeugungen, subjektive Theorien und professionelle Handlungsorientierungen kritisch. Sie entwickeln ihre Fähigkeit weiter, pädagogisches Handeln auch unter Bedingungen von Komplexität und Unsicherheit wissenschaftlich fundiert zu begründen und Verantwortung für individuelle Bildungs- und Entwicklungsprozesse zu übernehmen."]
    },
    "technikdidaktik-i":{
      contribution:"Vertiefung technikdidaktischer Analyse- und Gestaltungskompetenz zur wissenschaftlich fundierten Konzeption komplexer beruflicher Lehr-Lern-Prozesse.",
      contents:["Vertiefende technikdidaktische Theorien und Modelle","Analyse technischer Arbeits- und Geschäftsprozesse","Analyse beruflicher Anforderungssituationen und Kompetenzanforderungen","Fachsystematische und handlungssystematische Strukturierung technischer Lerngegenstände","Didaktische Analyse und Rekonstruktion technischer Inhalte","Entwicklung komplexer kompetenzorientierter Lernsituationen","Verschränkung von Situationshandlung und Lernhandlung","Repräsentation technischer Systeme und Prozesse","Analyse fachlicher Lernschwierigkeiten und Fehlvorstellungen","Theoriegeleitete Begründung und kritische Reflexion technikdidaktischer Entscheidungen"],
      qualification:["Die Studierenden verfügen über vertiefte Kenntnisse technikdidaktischer Theorien, Modelle und Gestaltungsprinzipien. Sie können komplexe technische Arbeits- und Handlungssituationen hinsichtlich ihrer fachlichen Struktur, beruflichen Anforderungen und didaktischen Potenziale analysieren sowie daraus begründete Anforderungen an die Gestaltung beruflicher Lehr-Lern-Prozesse ableiten.","Sie sind in der Lage, technische Lerngegenstände fachlich und didaktisch zu strukturieren und auf dieser Grundlage anspruchsvolle kompetenzorientierte Lehr-Lern-Prozesse eigenständig zu konzipieren. Dabei können sie fachsystematische und handlungssystematische Zugänge aufeinander beziehen, Situationshandlungen und systematische Lernhandlungen gezielt miteinander verschränken sowie unterschiedliche Repräsentations- und Gestaltungsmöglichkeiten technischer Lerngegenstände begründet auswählen.","Die Studierenden können alternative technikdidaktische Gestaltungsmöglichkeiten gegeneinander abwägen, eigene didaktische Entscheidungen theoriegeleitet begründen und hinsichtlich ihrer Voraussetzungen, Potenziale und Grenzen kritisch reflektieren. Sie entwickeln damit die Fähigkeit weiter, komplexe technische Bildungsprozesse wissenschaftlich fundiert und eigenständig zu konzipieren."]
    },
    "sps-ii":{
      contribution:"Weiterentwicklung professioneller Handlungskompetenz durch zunehmend selbstständige und adaptive Planung, Durchführung, Analyse und Reflexion beruflicher Lehr-Lern-Prozesse sowie die theoriegeleitete Begründung professioneller Handlungsentscheidungen.",
      contents:["Analyse und Berücksichtigung individueller Lernvoraussetzungen","Gestaltung kompetenzorientierter Lernsituationen","Adaptive Lernprozessbegleitung und Differenzierung","Diagnose, Feedback und Leistungsbewertung","Pädagogisches Handeln in komplexen Unterrichtssituationen","Theoriegeleitete Analyse und Evaluation eigenen Unterrichtshandelns","Systematische Nutzung von Feedback für die professionelle Weiterentwicklung","Reflexion professioneller Entscheidungen und Handlungsroutinen","Weiterentwicklung des eigenen professionellen Rollenverständnisses"],
      qualification:["Die Studierenden sind in der Lage, berufliche Lehr-Lern-Prozesse zunehmend selbstständig zu planen, durchzuführen und zu reflektieren. Sie berücksichtigen dabei curriculare Vorgaben, berufliche Handlungssituationen, fachliche und fachdidaktische Anforderungen sowie unterschiedliche Lernvoraussetzungen und treffen darauf bezogene didaktische und pädagogische Entscheidungen begründet.","Sie können Lern- und Kompetenzentwicklungsprozesse theoriegeleitet beobachten, diagnostische Informationen für ihr Unterrichtshandeln nutzen und Lehr-Lern-Prozesse situationsangemessen adaptieren. Formen der Lernprozessbegleitung, Differenzierung, des Feedbacks und der Leistungsbewertung setzen sie begründet und lernförderlich ein. Auch in komplexeren Unterrichtssituationen können sie Handlungsoptionen abwägen, situationsangemessen handeln und getroffene Entscheidungen nachträglich theoriegeleitet reflektieren.","Die Studierenden analysieren und evaluieren ihr eigenes professionelles Handeln und beziehen Beobachtungen, Rückmeldungen und wissenschaftliche Erkenntnisse systematisch in dessen Weiterentwicklung ein. Sie entwickeln damit ihre Fähigkeit weiter, berufliche Lehr-Lern-Prozesse zunehmend selbstständig, adaptiv und wissenschaftlich begründet zu gestalten und Verantwortung für die Lern- und Kompetenzentwicklung der Lernenden zu übernehmen."]
    },
    "qualitaet-team":{
      contribution:"Erweiterung professioneller Handlungskompetenz vom eigenen Unterricht auf die kooperative Gestaltung von Qualitäts-, Team- und Entwicklungsprozessen beruflicher Schulen als Organisationen.",
      contents:["Schule als Organisation und lernendes Handlungssystem","Grundlagen der Schul-, Organisations-, Personal- und Qualitätsentwicklung","Modelle und Verfahren schulischer Qualitätsentwicklung","Evaluation und datengestützte Schulentwicklung","Professionelle Kooperation und Teamarbeit","Kommunikation und Moderation in schulischen Entwicklungsprozessen","Rollen, Interessen und Verantwortlichkeiten schulischer Akteure","Gestaltung und Mitwirkung an schulischen Veränderungsprozessen","Umgang mit Konflikten und Widerständen","Innovation und Transformation beruflicher Schulen","Digitalisierung und KI als Gegenstände schulischer Entwicklungsprozesse"],
      qualification:["Die Studierenden verfügen über vertiefte Kenntnisse zentraler Ansätze der Schul-, Organisations-, Personal- und Qualitätsentwicklung und können berufliche Schulen als komplexe Organisationen und lernende Handlungssysteme analysieren. Sie können das Zusammenwirken individueller, kooperativer und organisationaler Bedingungen schulischer Qualität und Entwicklung theoriegeleitet beurteilen.","Sie sind in der Lage, schulische Entwicklungsbedarfe zu identifizieren, Daten und Evaluationsergebnisse zu interpretieren und daraus begründete Entwicklungsziele und -maßnahmen abzuleiten. Sie können Prozesse professioneller Kooperation und Teamarbeit analysieren und mitgestalten sowie Besprechungs-, Kooperations- und Entwicklungsprozesse zielgerichtet moderieren. Dabei können sie unterschiedliche Rollen, Interessen und Perspektiven schulischer Akteure berücksichtigen und mit Konflikten und Widerständen in Veränderungsprozessen konstruktiv umgehen.","Die Studierenden verstehen Schul- und Qualitätsentwicklung als Bestandteil professionellen Lehrerhandelns und können technologische, gesellschaftliche und organisationale Veränderungen hinsichtlich ihrer Bedeutung für die Entwicklung beruflicher Schulen beurteilen. Sie reflektieren ihre eigene Verantwortung für kooperative und organisationale Entwicklungsprozesse und entwickeln die Fähigkeit und Bereitschaft, diese evidenzorientiert, kooperativ und verantwortungsbewusst mitzugestalten und hinsichtlich ihrer Wirkungen zu reflektieren."]
    },
    "technikdidaktik-ii":{
      contribution:"Entwicklung eigenständiger technikdidaktischer Gestaltungs-, Diagnose- und Innovationskompetenz für komplexe technische Bildungsprozesse.",
      contents:["Adaptive Gestaltung technischer Lernprozesse","Verbindung fachpraktischen, fachtheoretischen und reflexiven Lernens","Diagnose technischer Kompetenzentwicklung","Kompetenzorientierte Leistungsfeststellung und -bewertung","Evaluation und Weiterentwicklung technischer Lehr-Lern-Arrangements","Digitale Technologien und KI in technischen Bildungsprozessen","Technologische Innovationen und Transformation beruflicher Arbeit","Konsequenzen technologischer Entwicklungen für Curricula und Lernsituationen","Entwicklung und Begründung eigener technikdidaktischer Konzeptionen"],
      qualification:["Die Studierenden sind in der Lage, komplexe technische Lehr-Lern-Prozesse eigenständig und unter Berücksichtigung unterschiedlicher Lern- und Kompetenzvoraussetzungen adaptiv zu gestalten. Sie können fachpraktisches, fachtheoretisches und reflexives Lernen systematisch miteinander verbinden und technikdidaktische Entscheidungen situationsangemessen treffen und wissenschaftlich begründen.","Sie können Lern- und Kompetenzentwicklungsprozesse diagnostizieren, geeignete Verfahren der Leistungsfeststellung und -bewertung auswählen und deren Ergebnisse zur Analyse und adaptiven Weiterentwicklung technischer Lehr-Lern-Prozesse nutzen. Sie sind in der Lage, technikdidaktische Arrangements anhand wissenschaftlich begründeter Kriterien zu evaluieren und daraus Konsequenzen für deren systematische Weiterentwicklung abzuleiten.","Die Studierenden können digitale und KI-basierte Technologien hinsichtlich ihrer fachlichen und didaktischen Potenziale und Grenzen beurteilen und begründet in technische Bildungsprozesse integrieren. Sie analysieren technologische Innovationen hinsichtlich ihrer Auswirkungen auf berufliche Tätigkeiten, Kompetenzanforderungen und Curricula und leiten daraus begründete Konsequenzen für die Weiterentwicklung technischer Bildungsprozesse ab. Sie entwickeln damit die Fähigkeit, technikdidaktische Konzepte eigenständig, evidenzorientiert und unter Bedingungen technologischen Wandels weiterzuentwickeln."]
    },
    "fachdidaktisches-praktikum":{
      contribution:"Weiterentwicklung eigenständiger technikdidaktischer Handlungskompetenz durch die theoriegeleitete Gestaltung, Durchführung, Analyse und Weiterentwicklung komplexer technischer Lehr-Lern-Prozesse in enger Verzahnung mit Technikdidaktik III.",
      contents:["Erprobung und Weiterentwicklung kompetenzorientierter Lernsituationen","Analyse und Berücksichtigung fachlicher und beruflicher Lernvoraussetzungen","Adaptive Gestaltung und Begleitung technischer Lernprozesse","Erprobung von Verfahren zur Diagnose technischer Kompetenzentwicklung","Gestaltung und Reflexion von Feedback und kompetenzorientierter Leistungsbewertung","Erprobung digitaler und KI-basierter Technologien in technischen Lehr-Lern-Prozessen","Theoriegeleitete Beobachtung und Analyse eigenen und fremden Unterrichts","Kollegiale Unterrichtsplanung, Hospitation und Peer-Feedback","Systematische Evaluation und Weiterentwicklung eigener Unterrichtskonzepte","Kontinuierliche Rückbindung schulpraktischer Erfahrungen an Technikdidaktik III"],
      qualification:["Die Studierenden sind in der Lage, komplexe technische Lehr-Lern-Prozesse auf Grundlage beruflicher Anforderungssituationen, curricularer Vorgaben und technikdidaktischer Erkenntnisse weitgehend selbstständig zu planen, durchzuführen und zu reflektieren. Sie berücksichtigen dabei unterschiedliche fachliche und berufliche Lernvoraussetzungen und gestalten technische Lernprozesse situationsangemessen und adaptiv.","Sie können Lern- und Kompetenzentwicklungsprozesse theoriegeleitet beobachten und analysieren, diagnostische Informationen für ihr Unterrichtshandeln nutzen sowie geeignete Formen der Lernprozessbegleitung, des Feedbacks und der Leistungsbewertung praktisch erproben und hinsichtlich ihrer Wirkungen reflektieren. Digitale und KI-basierte Technologien können sie didaktisch begründet einsetzen und deren Funktion und Wirkung im konkreten Lehr-Lern-Prozess kritisch beurteilen.","Die Studierenden analysieren und evaluieren ihr eigenes technikdidaktisches Handeln anhand wissenschaftlich begründeter Kriterien und nutzen Beobachtungen, Rückmeldungen, Hospitationen und kollegiale Reflexion zur systematischen Weiterentwicklung ihrer Unterrichtskonzepte und ihres professionellen Handelns. Sie sind in der Lage, schulpraktische Erfahrungen mit den in Technikdidaktik III erarbeiteten theoretischen und konzeptionellen Erkenntnissen systematisch in Beziehung zu setzen und daraus begründete Konsequenzen für die weitere Gestaltung technischer Lehr-Lern-Prozesse abzuleiten."]
    },
    "forschungsseminar-ma":{
      contribution:"Entwicklung eigenständiger berufspädagogischer und technikdidaktischer Forschungskompetenz als Bestandteil wissenschaftlich fundierter professioneller Könnerschaft.",
      contents:["Entwicklung und theoretische Präzisierung berufspädagogischer und technikdidaktischer Forschungsfragen","Systematische Erschließung und kritische Einordnung des Forschungsstands","Theoriegeleitete Entwicklung von Forschungsmodellen und Untersuchungsdesigns","Qualitative, quantitative und Mixed-Methods-Forschungsansätze","Entwicklung und Auswahl geeigneter Erhebungsinstrumente","Verfahren der Datenaufbereitung und -auswertung","Gütekriterien berufspädagogischer und technikdidaktischer Forschung","Forschungsethik und wissenschaftliche Integrität","Theoriebezogene Interpretation und Diskussion empirischer Ergebnisse","Planung, Präsentation und kollegiale Diskussion eigener Forschungsvorhaben","Vorbereitung und Begleitung der Masterarbeit"],
      qualification:["Die Studierenden sind in der Lage, komplexe berufspädagogische und technikdidaktische Problemstellungen in wissenschaftlich bearbeitbare Forschungsfragen zu überführen und den relevanten Forschungsstand systematisch zu erschließen und kritisch einzuordnen.","Sie können theoretische Bezugssysteme, Forschungsfragen und methodische Vorgehensweisen konsistent aufeinander beziehen und ein geeignetes Untersuchungsdesign weitgehend selbstständig entwickeln. Sie sind in der Lage, geeignete Verfahren der Datenerhebung und -auswertung auszuwählen, deren Möglichkeiten und Grenzen zu beurteilen sowie empirische Ergebnisse theoriebezogen zu interpretieren.","Die Studierenden reflektieren Gütekriterien, Limitationen und forschungsethische Anforderungen des eigenen wissenschaftlichen Handelns. Sie entwickeln damit die Fähigkeit, ein berufspädagogisches oder technikdidaktisches Forschungsprojekt weitgehend selbstständig zu konzipieren, durchzuführen, kritisch zu reflektieren und wissenschaftlich zu kommunizieren."]
    },
    "masterarbeit":{
      contribution:"Vertiefung und Nachweis eigenständiger wissenschaftlicher Forschungs- und Reflexionskompetenz durch die theoriegeleitete und methodisch fundierte Bearbeitung einer komplexen berufspädagogischen oder technikdidaktischen Problemstellung.",
      contents:["Systematische Analyse und kritische Einordnung des relevanten Forschungsstands","Entwicklung und theoretische Fundierung einer eigenständigen Forschungsfrage","Entwicklung eines konsistenten theoretischen bzw. analytischen Bezugsrahmens","Eigenständige Auswahl, Entwicklung und Begründung eines geeigneten Forschungsdesigns","Gegebenenfalls Entwicklung bzw. begründete Auswahl geeigneter Erhebungs- und Auswertungsverfahren","Eigenständige Durchführung und methodisch kontrollierte Auswertung einer empirischen Untersuchung","Theoriebezogene Interpretation und Diskussion der Ergebnisse","Kritische Reflexion von Methodik, Güte, Aussagekraft und Limitationen","Ableitung wissenschaftlicher und gegebenenfalls berufspädagogisch-didaktischer Implikationen","Wissenschaftliche Dokumentation, Diskussion und Einordnung des erzielten Erkenntnisbeitrags"],
      qualification:["Die Studierenden weisen nach, dass sie eine komplexe berufspädagogische oder technikdidaktische Problemstellung innerhalb eines vorgegebenen Zeitraums weitgehend selbstständig wissenschaftlich untersuchen können. Sie sind in der Lage, den relevanten Forschungsstand systematisch zu analysieren, eine theoretisch fundierte Forschungsfrage zu entwickeln und diese in ein konsistentes theoretisches und methodisches Untersuchungsdesign zu überführen.","Sie können wissenschaftliche Methoden begründet auswählen und anwenden, empirische oder theoretisch gewonnene Ergebnisse methodisch kontrolliert analysieren und diese vor dem Hintergrund des Forschungsstands und des gewählten theoretischen Bezugsrahmens interpretieren. Alternative Interpretationen, methodische Grenzen und die Reichweite eigener Aussagen können sie kritisch beurteilen.","Die Studierenden sind in der Lage, aus ihrer Untersuchung begründete wissenschaftliche und gegebenenfalls berufspädagogisch-didaktische Schlussfolgerungen abzuleiten und den eigenständigen Erkenntnisbeitrag ihrer Arbeit zu bestimmen. Sie zeigen damit die Fähigkeit zu weitgehend selbstständigem, theoriegeleitetem, methodisch reflektiertem und wissenschaftlich verantwortlichem Forschen."]
    }
  },
  modules: {
    "begleitetes-sps-i":{title:"Begleitetes SPS I",phase:"Bachelor",semester:"3. Semester",lp:"5 LP · Alternative zu SPS I",contribution:"Intensiv verzahnter Praxis-Theorie-Entwicklungsraum an der Universitätsberufsschule.",contents:["theoriegeleitete Praxisbeobachtung","erste Unterrichtserprobungen","enge Verzahnung mit Technikdidaktik I"],objective:"Berufsschulische Praxis theoriegeleitet beobachten, planen, erproben und reflektieren.",development:"verstehen ↔ planen ↔ erproben ↔ reflektieren",links:["Technikdidaktik I","Universitätsberufsschule"]},
    "berufspaedagogik-ii":{title:"Berufspädagogik II",phase:"Master",semester:"1. Semester",lp:"5 LP · Tandem A",contribution:"Analytischer und modellgestützter Bezugsrahmen für die Planung beruflichen Unterrichts.",contents:["Bayreuther Kompetenzmatrix","Bayreuther Modell der Unterrichtsvorbereitung","modellgestützte Planung"],objective:"Komplexe Bildungsprozesse analysieren und begründete Handlungsoptionen entwickeln.",development:"Modell verstehen ↔ Unterricht planen ↔ begründen",links:["SPS II","Universitätsberufsschule"]},
    "sps-ii":{title:"SPS II",phase:"Master",semester:"1. Semester",lp:"5 LP · Tandem A",contribution:"Anwendungs-, Erprobungs- und Reflexionsraum für die modellgestützte Unterrichtsplanung.",contents:["Anwendung","Erprobung","Beobachtung","Reflexion"],objective:"Lehr-Lern-Prozesse zunehmend selbstständig planen, durchführen und reflektieren.",development:"Planung ↔ Praxis ↔ Beobachtung ↔ Reflexion",links:["Berufspädagogik II","Universitätsberufsschule"]},
    "technikdidaktik-ii":{title:"Technikdidaktik III",phase:"Master",semester:"2. Semester",lp:"5 LP · Tandem B",contribution:"Planung und Realität werden systematisch aufeinander bezogen; Subjektive Theorien werden expliziert und elaboriert.",contents:["Umsetzung","Beobachtung","Reflexion","Elaboration Subjektiver Theorien","Veränderung und erneute Erprobung"],objective:"Komplexe technikdidaktische Problemstellungen selbstständig bearbeiten.",development:"Umsetzung ↔ Beobachtung ↔ Reflexion ↔ Elaboration",links:["Fachdidaktisches Praktikum","Subjektive Theorien","Universitätsberufsschule"]},
    "fachdidaktisches-praktikum":{title:"Fachdidaktisches Praktikum",phase:"Master",semester:"2. Semester",lp:"5 LP · Tandem B",contribution:"Praxisraum für Umsetzung, Beobachtung und erneute Erprobung weiterentwickelter Planungen.",contents:["Unterricht umsetzen","Lernprozesse beobachten","Diskrepanzen analysieren","Veränderungen erproben"],objective:"Unterricht theoriegeleitet umsetzen, analysieren und weiterentwickeln.",development:"Planung ↔ Umsetzung ↔ Veränderung ↔ erneute Erprobung",links:["Technikdidaktik III","Subjektive Theorien","Universitätsberufsschule"]},
    "qualitaet-team":{title:"Qualitäts- und Teamentwicklung",phase:"Master",semester:"1. Semester",lp:"5 LP",contribution:"Perspektiverweiterung vom individuellen Handeln auf Team, Organisation und Schule als lernendes System.",contents:["Schulentwicklung","Qualitätsmanagement","QmbS","Lehrerklassenteams"],objective:"Kooperative und organisationale Entwicklungsprozesse analysieren und mitgestalten.",development:"Handeln ↔ Kooperation ↔ Team ↔ Organisation",links:["Schule als lernendes System"]}
  },
  concepts: {
    development:{
      title:"Gestufte Kompetenzentwicklung",
      kicker:"Curriculares Progressionsprinzip",
      text:"Die Veranstaltungen bilden keine lose Folge einzelner Wissensbestände. Sie sind als aufeinander bezogene Entwicklungsräume angelegt, in denen berufspädagogisches, technikdidaktisches und wissenschaftliches Wissen schrittweise mit praktischer Erfahrung, Reflexion und verantwortlichem Handeln verbunden wird. Die Anforderungen steigen über Bachelor, Master und die weiteren Phasen der Lehrkräftebildung hinweg, ohne dass frühere Kompetenzbereiche abgeschlossen oder ersetzt werden.",
      sections:[
        {title:"Entwicklungsbewegung im Bachelor",text:"Der Bachelor legt die fachlichen, pädagogisch-psychologischen, berufspädagogischen und technikdidaktischen Grundlagen. Die Studierenden erschließen berufliche Bildung und berufliche Arbeit, analysieren Lern- und Handlungssituationen, planen erste Lehr-Lern-Prozesse und erproben diese begleitet in schulischer Praxis. Reflexion und Forschung helfen dabei, Erfahrungen wissenschaftlich einzuordnen und eigene subjektive Theorien sichtbar zu machen.",steps:["verstehen und begrifflich einordnen","berufliche und pädagogische Situationen analysieren","Lehr-Lern-Prozesse begründet planen","pädagogisch-didaktisches Handeln begleitet erproben","Erfahrungen und eigenes Handeln theoriegeleitet reflektieren","berufliche Bildungsprobleme wissenschaftlich untersuchen"]},
        {title:"Entwicklungsbewegung im Master",text:"Im Master werden die erworbenen Grundlagen auf komplexere, offenere und weniger eindeutig strukturierte Situationen bezogen. Unterricht wird zunehmend selbstständig, adaptiv und diagnostisch fundiert gestaltet. Zugleich erweitert sich die Perspektive vom eigenen Unterricht auf Kooperation, Schulentwicklung, technologische Transformation und eigenständige Forschung.",steps:["Wissen und Analysemodelle vertiefen","komplexe Lehr-Lern-Prozesse selbstständig gestalten","situationsbezogen und adaptiv entscheiden","Diagnose, Feedback und Evaluation systematisch nutzen","Team, Organisation und Schule mitgestalten","Entscheidungen theoretisch und evidenzbezogen begründen","eigenständige Forschung konzipieren und durchführen"]},
        {title:"Zunehmende professionelle Anforderungen",items:["Komplexität: von überschaubaren Grundlagen und ersten Planungen zu mehrdeutigen beruflichen, pädagogischen und organisationalen Situationen.","Eigenständigkeit: von angeleiteter Analyse und Erprobung zu selbstständiger Planung, Entscheidung, Evaluation und Forschung.","Situationsbezogenheit: von allgemeinen Konzepten zu adaptivem Handeln unter konkreten fachlichen, sozialen und institutionellen Bedingungen.","Reflexivität: von der Beschreibung eigener Erfahrungen zur kritischen Prüfung subjektiver Theorien, Entscheidungen, Wirkungen und Grenzen.","Verantwortung: vom eigenen Lern- und Unterrichtshandeln zur Mitverantwortung für Lernende, Teams, Schule und berufliche Bildung."]},
        {title:"Rekursive statt lineare Entwicklung",text:"Kompetenzentwicklung verläuft nicht als einmalige Abfolge abgeschlossener Stufen. Wissenschaftliche Theorie eröffnet neue Perspektiven auf Praxis; praktische Erfahrungen konkretisieren, irritieren und prüfen theoretische Annahmen. Beobachtung, Feedback und Reflexion führen zu veränderten Planungen und erneuter Erprobung. Spätere Studienabschnitte greifen frühere Wissens- und Erfahrungsbestände deshalb wieder auf, differenzieren sie und machen sie zunehmend handlungswirksam."},
        {title:"Zusammenspiel von Wissen, Können und Wollen",items:["Wissen schafft begriffliche, theoretische und empirische Grundlagen für Analyse, Begründung und Reflexion.","Können entsteht in der situationsbezogenen Planung, Durchführung, Beobachtung und Weiterentwicklung professionellen Handelns.","Wollen umfasst Werte, Haltungen, Motivation und die Bereitschaft, Wissen und Können verantwortlich einzusetzen."],note:"Professionelle Könnerschaft entsteht nicht durch die Addition einzelner Teilkompetenzen, sondern durch ihr zunehmend situationsangemessenes und verantwortliches Zusammenwirken."},
        {title:"Phasenübergreifende Perspektive",text:"Mit Bachelor und Master ist die Entwicklung nicht abgeschlossen. Das Referendariat verdichtet wissenschaftlich fundierte Wissens- und Reflexionsbestände im eigenverantwortlichen beruflichen Handeln. Fort- und Weiterbildung greifen neue Anforderungen aus Beruf, Technik, Gesellschaft und Schule auf und führen die Professionalisierung bedarfsbezogen und forschungsinformiert weiter."},
        {title:"Übergeordnetes Entwicklungsziel",text:"Ziel ist eine KI-souveräne berufspädagogisch-didaktische Könnerschaft: Lehrkräfte verbinden Wissen, Können und Wollen in den Handlungsbereichen Pädagogik, Didaktik und Beruf. Sie können auch unter Bedingungen technologischer Transformation begründet entscheiden, situationsangemessen handeln, Wirkungen reflektieren und professionelle Verantwortung übernehmen."}
      ],
      sequence:"verstehen → analysieren → planen → erproben → reflektieren → vertiefen → selbstständig und adaptiv handeln → systemisch gestalten → eigenständig forschen → Professionalisierung fortführen",
      links:["Bachelor- und Mastermodule als aufeinander bezogene Entwicklungsräume","Rekursive Praxis-Theorie-Verzahnung","Subjektive Theorien als handlungsleitende Strukturen","KI-souveräne berufspädagogisch-didaktische Könnerschaft","Referendariat sowie Fort- und Weiterbildung"]
    },
    subjective:{
      title:"Forschungsprogramm Subjektive Theorien",
      kicker:"Professionstheoretische Grundlage",
      text:"Das Forschungsprogramm begreift den Menschen als erkenntnis-, sprach-, kommunikations- und handlungsfähiges Subjekt. Subjektive Theorien sind komplexe Aggregate von Konzepten mit zumindest impliziter Argumentationsstruktur. Sie konstituieren Situationen, erklären und prognostizieren Ereignisse, generieren Handlungsentwürfe und werden in konkreten Situationen handlungsleitend wirksam.",
      sections:[
        {title:"Epistemologisches Subjektmodell",text:"Im Zentrum stehen die potenzielle Rationalität sowie Intentionalität, Reflexivität und Autonomie des Menschen. Forschende und Handelnde werden nicht in einer starren Subjekt-Objekt-Relation gedacht: Das handelnde Subjekt ist zur Selbst- und Welterkenntnis sowie zur kommunikativen Verständigung fähig.",refs:"Groeben & Scheele (1977, 2020); Groeben et al. (1988)"},
        {title:"Charakteristika Subjektiver Theorien",items:["Kognitionen der Selbst- und Weltsicht","relativ stabile, durch Erfahrung veränderbare mentale Repräsentationen","teils bewusste, teils implizite Strukturen","komplexe Verknüpfungen mit zumindest impliziten Wenn-dann-Beziehungen","im Dialog-Konsens aktualisierbar und rekonstruierbar","hinsichtlich ihrer Funktionen wissenschaftlich zu prüfen"],refs:"Groeben et al. (1988); Dann (1994); Scheele & Groeben (1984, 2020)"},
        {title:"Theorieähnliche Funktionen",items:["Situationen definieren und Wirklichkeit konstituieren","eingetretene Ereignisse erklären und teilweise rechtfertigen","künftige Ereignisse prognostizieren und Erwartungen bilden","Handlungsentwürfe zur Herbeiführung erwünschter oder Vermeidung unerwünschter Ereignisse generieren"],refs:"Groeben et al. (1988); Dann (1994)"},
        {title:"Reichweite und Handlungsnähe",text:"Subjektive Theorien großer und mittlerer Reichweite sind vergleichsweise leicht verbalisierbar, reflektierbar und veränderbar, stehen aber häufig weiter vom Handeln unter Druck entfernt. Verdichtete Subjektive Theorien geringer Reichweite sind besonders handlungsrelevant, zugleich jedoch schwerer zugänglich und im Handlungsvollzug schwer veränderbar.",figure:{src:"Hintergrundwissen/Abbildung%20SubjektiveTheorieReichweite.pdf",title:"Subjektive Theorien, ihre Reichweiten und Einflüsse",caption:"Zusammenhang von Veränderungspotenzial, Handlungsrelevanz und Handeln (Dier, 2024; in Anlehnung an Wahl 1991, 2013, 2020)."},refs:"Wahl (1991, 2013, 2020)"},
        {title:"Professionalisierungslogik",steps:["eigene praktische Erfahrung als Aktivierungsanlass","Subjektive Theorien rekonstruieren und kommunikativ validieren","mit objektiven wissenschaftlichen Theorien konfrontieren und explanativ prüfen","Subjektive Theorien zielgerichtet elaborieren","weiterentwickelte Strukturen erneut praktisch erproben und im Handeln verdichten"],refs:"Wahl (2001, 2002, 2020); Dann (2008); Borko & Putnam (1996); Reusser & Pauli (2014)"},
        {title:"Konsequenz für die Lehrkräftebildung",text:"Subjektive Theorien bestehen bereits vor dem Studium und beeinflussen dessen Entwicklungsprozesse. Sie sollen nicht schlicht ersetzt werden. Entscheidend ist ihre wissenschaftlich angeleitete, praxisbezogene Weiterentwicklung, damit Veränderungen nicht auf der Ebene verbalisierbarer Vorstellungen verbleiben, sondern im professionellen Handeln wirksam werden.",refs:"Lortie (1975); Messner (2002); Dann (2008); Wenzl (2020); Dier (2024)"}
      ],
      sequence:"praktische Erfahrung ↔ Aktivierung und Rekonstruktion ↔ wissenschaftliche Konfrontation und Elaboration ↔ erneutes professionelles Handeln",
      sourceGroups:[
        {title:"Grundlagen des Forschungsprogramms",entries:["Groeben & Scheele (1977, 2020)","Groeben et al. (1988)","Scheele & Groeben (1984, 2020)"]},
        {title:"Handlungsleitung und Reichweite",entries:["Dann (1994)","Wahl (1991, 2013, 2020)"]},
        {title:"Professionalisierung und Lehrkräftebildung",entries:["Lortie (1975)","Borko & Putnam (1996)","Messner (2002)","Dann (2008)","Reusser & Pauli (2014)","Wenzl (2020)","Dier (2024)"]}
      ],
      links:["Begleitetes SPS I","Berufspädagogik II ↔ SPS II","Technikdidaktik III ↔ Fachdidaktisches Praktikum","Forschungsseminare und Forschungsarbeiten"]
    },
    cycle:{
      title:"Rekursive Praxis-Theorie-Verzahnung",
      kicker:"Curriculares Entwicklungsprinzip",
      text:"Wissenschaftliche Theorie und berufsschulische Praxis sind eigenständige, aber wechselseitig aufeinander bezogene Erkenntnis- und Entwicklungsräume. Theorie eröffnet Perspektiven für die Analyse und Gestaltung von Unterricht; Praxis konkretisiert, irritiert und prüft theoretische Annahmen. Die dabei gewonnenen Erkenntnisse fließen erneut in Theorie, Planung und professionelles Handeln ein.",
      sections:[
        {title:"Was Verzahnung bedeutet",text:"Praxis-Theorie-Verzahnung ist weder die einfache Anwendung wissenschaftlicher Theorie auf schulische Praxis noch eine unreflektierte Ableitung allgemeiner Aussagen aus einzelnen Erfahrungen. Beide Bereiche behalten ihre eigene Logik und werden in einem professionell begleiteten Entwicklungsprozess systematisch aufeinander bezogen."},
        {title:"Theoriegeleitet Praxis gestalten",items:["wissenschaftliche Begriffe und Modelle als Beobachtungs- und Analyseinstrumente nutzen","Unterricht begründet planen und Handlungsalternativen antizipieren","Entscheidungen transparent und fachlich nachvollziehbar machen","theoretische Annahmen in konkreten Situationen erproben","Wirkungen des eigenen Handelns systematisch beobachten"]},
        {title:"Praxisbasiert Theorie weiterentwickeln",items:["praktische Erfahrungen als Fragen und Irritationen aufnehmen","Passung und Reichweite theoretischer Konzepte prüfen","Bedingungen, Grenzen und Widersprüche sichtbar machen","Modelle anhand konkreter Fälle differenzieren und kontextualisieren","aus systematisch untersuchter Praxis Forschungs- und Entwicklungsimpulse gewinnen"]},
        {title:"Rekursion als spiralförmige Entwicklung",text:"Erkenntnisse werden in den Ausgangsprozess zurückgeführt. Jede praktische Erprobung kann neue Fragen erzeugen; jede theoretische Klärung verändert die Wahrnehmung und Gestaltung nachfolgender Praxis. Der Kreislauf wiederholt sich deshalb nicht identisch, sondern entwickelt sich spiralförmig weiter. Nach dem ersten Durchlauf lässt sich kein eindeutiges ‚zuerst Theorie‘ oder ‚zuerst Praxis‘ mehr bestimmen."},
        {title:"Subjektive Theorien als Vermittlungsinstanz",text:"Subjektive Theorien beeinflussen, was eine Person wahrnimmt, wie sie Situationen deutet, welche Entscheidungen sie trifft und wie sie handelt. In der Verzahnung werden sie durch praktische Erfahrungen aktiviert, in Reflexion und Feedback expliziert, mit wissenschaftlichen Theorien konfrontiert, elaboriert und anschließend erneut praktisch erprobt."},
        {title:"Das Reflexions-Feedback-Modell als operative Konkretisierung",text:"Das Modell übersetzt die Praxis-Theorie-Verzahnung in einen wiederkehrenden, professionell begleiteten Arbeitsprozess. Der Innenkreis strukturiert die Selbstreflexion und Handlungsentwicklung der handelnden Person: Auf die Action folgen der Blick zurück, die Fokussierung wesentlicher Aspekte, der theoriebezogene Blick nach vorn und die Entwicklung begründeter Handlungsalternativen. Der Außenkreis ergänzt die Perspektiven der Hospitierenden und Dozierenden durch Feed Back, Feed Up und Feed Forward. Die erneute Action führt die weiterentwickelten Subjektiven Theorien in die Praxis zurück und eröffnet den nächsten Durchlauf.",figure:{src:"Hintergrundwissen/Abbildung%20reffeedmodOBJ.pdf",title:"Digital unterstütztes Reflexions-Feedback-Modell",caption:"Digital unterstütztes Reflexions-Feedback-Modell der gewerblich-technischen Universitätsberufsschule Bayreuth (Dier, 2024), in Anlehnung an Korthagen und Kessels (1999), Hattie und Timperley (2007) sowie Jahncke (2019).",aspect:"1340 / 748"},refs:"Korthagen et al. (2001); Korthagen (2017); Jahncke (2019); Hattie & Timperley (2007); Dier (2024)"},
        {title:"Qualitätsbedingungen gelingender Verzahnung",items:["reale und relevante berufsschulische Handlungssituationen","systematische Beobachtung statt bloßer Praxisteilnahme","zeitnahe Selbstreflexion und qualifiziertes Fremdfeedback","wissenschaftliche Modelle mit erkennbarer Passung zur Situation","geschützte Erprobungs- und Entwicklungsräume","erneute Anwendung veränderter Handlungsentwürfe","professionelle Begleitung mit wissenschaftlicher und schulpraktischer Expertise","curriculare Kontinuität über einzelne Veranstaltungen hinaus"],refs:"Entscheidend ist nicht die bloße Menge an Praxis, sondern die Qualität ihrer wissenschaftlichen Vorbereitung, Begleitung, Reflexion und Rückkopplung."},
        {title:"Lehren und Lernen",text:"Praxis beobachten, Unterricht theoriegeleitet planen, Handeln erproben, Erfahrungen reflektieren und veränderte Handlungsoptionen erneut umsetzen."},
        {title:"Forschung und Entwicklung",text:"Praxis theoriegeleitet untersuchen und mitgestalten sowie aus systematisch ausgewerteter Praxis theoretische Modelle prüfen, differenzieren oder weiterentwickeln."},
        {title:"Konsequenz für die Lehrkräftebildung",text:"Praxis-Theorie-Verzahnung ist kein einzelner curricularer Baustein, sondern ein durchgängiges Entwicklungsprinzip der phasenübergreifenden Lehrkräftebildung. Ihr Ziel ist eine professionelle Könnerschaft, in der wissenschaftliches Wissen, reflektierte Erfahrung und situationsangemessenes Handeln dauerhaft aufeinander bezogen werden."}
      ],
      sequence:"erleben und beobachten → reflektieren und explizieren → wissenschaftlich analysieren → Handlungsoptionen entwickeln → planen und erproben → Wirkungen beobachten → erneut reflektieren",
      sourceGroups:[
        {title:"Praxis-Theorie-Verhältnis",entries:["Korthagen, Kessels, Koster, Lagerwerf & Wubbels (2001): Linking Practice and Theory: The Pedagogy of Realistic Teacher Education","Korthagen & Kessels (1999): Linking Theory and Practice: Changing the Pedagogy of Teacher Education","Neuweg (2005, 2011, 2022)","Cramer (2013, 2014)","Caruso et al. (2021)"]},
        {title:"Reflexionszyklus und professionelles Lernen",entries:["Korthagen et al. (2001): ALACT-Modell","Korthagen (2017): Inconvenient Truths about Teacher Learning: Towards Professional Development 3.0","Jahncke (2019): (Selbst-)Reflexionsfähigkeit – Modellierung, Differenzierung und Beförderung mittels eines Kompetenzentwicklungsportfolios"]},
        {title:"Feedback und Entwicklungssteuerung",entries:["Hattie & Timperley (2007): The Power of Feedback","Sadler (1989): Formative Assessment and the Design of Instructional Systems"]},
        {title:"Universitätsberufsschule und Reflexions-Feedback-Modell",entries:["Müller (2020): Mikromethodisches Ursprungskonzept der gewerblich-technischen Universitätsschule Bayreuth","Dier (2024): Ausdifferenziertes und digital unterstütztes Reflexions-Feedback-Modell"]}
      ],
      links:["Begleitetes SPS I ↔ Technikdidaktik I","Berufspädagogik II ↔ SPS II","Technikdidaktik III ↔ Fachdidaktisches Praktikum","Forschungsseminare und Forschungsarbeiten","Universitätsberufsschule als Lehr-, Praxis- und Forschungsraum"],
      articleLinks:[
        {label:"Lehr-Lern-Konzept zur Praxis-Theorie-Verzahnung",href:"../assets/docs/Lehr-Lern-Konzept-MDier.pdf"}
      ]
    },
    competence:{
      title:"KI-souveräne berufspädagogisch-didaktische Könnerschaft",
      kicker:"Ziel professioneller Entwicklung · KI-bpd-K",
      text:"KI-bpd-K bezeichnet eine spezifische Form professioneller Handlungskompetenz von Lehrkräften an beruflichen Schulen. Sie verbindet situative Anpassungsfähigkeit und intuitive Flexibilität mit reflektiertem, wissenschaftlich fundiertem und wertorientiertem Handeln – auch und gerade unter den Bedingungen Künstlicher Intelligenz.",
      sections:[
        {title:"Drei Kompetenzdimensionen",items:["Wissen umfasst theoretische und empirische Erkenntnisse, die Orientierung, Begründung und Reflexion ermöglichen.","Können bezeichnet die situationsgerechte Bewältigung beruflicher Anforderungen und entwickelt sich durch eigenes, reflektiertes Handeln.","Wollen bündelt Werte, Haltungen, Motivation und die Bereitschaft, Wissen und Können verantwortlich einzusetzen."],note:"Die Dimensionen werden nicht additiv verstanden: Erst ihr Zusammenwirken ermöglicht Könnerschaft."},
        {title:"Mutualistische Symbiose",text:"Wissen, Können und Wollen bewahren ihre Eigenständigkeit und bereichern sich zugleich wechselseitig. Keine Dimension dominiert: Wissen orientiert und begründet, Können realisiert situationsangemessen, Wollen vermittelt wertbezogen und übernimmt Verantwortung. Könnerschaft entsteht damit nicht durch Wissen oder Routine allein, sondern in ihrer handlungswirksamen Interdependenz."},
        {title:"Drei berufliche Handlungsbereiche",items:["Pädagogik: Bildungsauftrag bestimmen, Lernende begleiten und pädagogisch verantwortlich handeln.","Didaktik: Lehr-Lern-Prozesse begründet planen, gestalten, analysieren und weiterentwickeln.","Beruf: Berufe, Geschäfts- und Arbeitsprozesse sowie die dafür erforderlichen fachlichen und überfachlichen Anforderungen erschließen."],note:"In jedem Bereich werden Wissen, Können und Wollen benötigt und auf konkrete Anforderungssituationen bezogen."},
        {title:"KI-Souveränität",text:"KI-souveräne Lehrkräfte entscheiden aktiv, kritisch und selbstbestimmt, ob, wie und wann KI pädagogisch, didaktisch und beruflich sinnvoll eingesetzt wird. Dazu gehören technisch-informatische Grundlagen, ethische Urteilsfähigkeit und fachliche Reflexivität. KI erweitert Denk-, Entscheidungs- und Handlungsspielräume, ersetzt aber weder menschliche Entscheidungshoheit noch professionelle Verantwortung."},
        {title:"Schule als lernendes System",text:"Professionelle Könnerschaft entfaltet sich nicht nur im Klassenzimmer. Individuelles Handeln, kollegiale Kooperation und organisationale Schulentwicklung beeinflussen sich wechselseitig. Die Lehrkraft gestaltet Unterricht und wirkt zugleich an gemeinsamen Reflexions-, Berufsbildungs- und Entwicklungsprozessen der Schule mit."},
        {title:"Bedeutung für die Lehrkräftebildung",text:"Das Modell fungiert als übergeordnetes Ziel der phasenübergreifenden Professionalisierung. Module und Praxisräume leisten unterschiedliche Beiträge zur Entwicklung der Dimensionen und Handlungsbereiche. In rekursiven Praxis-Theorie-Prozessen werden wissenschaftliches Wissen, reflektierte Erfahrung, Haltung und situationsangemessenes Handeln zunehmend miteinander verschränkt."},
        {title:"Modellarchitektur",text:"Die Modellarchitektur macht sichtbar, dass KI-Souveränität aus dem wechselseitigen Zusammenspiel von Wissen, Können und Wollen in den Handlungsbereichen Pädagogik, Didaktik und Beruf entsteht.",figure:{src:"Hintergrundwissen/Abbildung%20KI-souvera%CC%88ne%20berufspa%CC%88dagogisch-didaktische%20Ko%CC%88nnerschaft.pdf",title:"KI-bpd-K · Modellübersicht",caption:"Modell der KI-souveränen berufspädagogisch-didaktischen Könnerschaft (Dier, Artikelentwurf 2026).",aspect:"595 / 842"}}
      ],
      sequence:"Wissen ↔ Können ↔ Wollen · in Pädagogik, Didaktik und Beruf · rekursiv über Studium, Referendariat sowie Fort- und Weiterbildung entwickeln",
      links:["Subjektive Theorien als handlungsleitende Strukturen","Rekursive Praxis-Theorie-Verzahnung","Universitätsberufsschule als Entwicklungsraum","Gestufte Kompetenzentwicklung"],
      articleLinks:[
        {label:"Artikel zur KI-souveränen berufspädagogisch-didaktischen Könnerschaft",href:"../assets/docs/KI-souveraene-berufspaedagogisch-didaktische-Koennerschaft.pdf"}
      ],
      sourceGroups:[
        {title:"Kompetenz und berufliches Handeln",entries:["Weinert (2001): Vergleichende Leistungsmessung in Schulen – eine umstrittene Selbstverständlichkeit","Müller (2016): Handlungskompetenzmatrix – Eine Planungshilfe für kompetenzorientiertes Unterrichten an der Berufsschule"]},
        {title:"Pädagogische Könnerschaft und Theorie-Praxis-Verhältnis",entries:["Neuweg (2005): Emergenzbedingungen pädagogischer Könnerschaft","Neuweg (2020): Könnerschaft und implizites Wissen","Neuweg (2021): Lehrerkompetenz im Spannungsfeld von Wissen und Können","Neuweg (2022): Lehrerbildung – Zwölf Denkfiguren im Spannungsfeld von Wissen und Können"]},
        {title:"KI, professionelles Denken und Handeln",entries:["Chiriatti, Ganapini, Panai et al. (2024): The Case for Human–AI Interaction as System 0 Thinking","Mishra & Koehler (2006): Technological Pedagogical Content Knowledge","Redecker (2017): European Framework for the Digital Competence of Educators – DigCompEdu"]},
        {title:"Schule als lernendes System",entries:["Luhmann (1984): Soziale Systeme","Altrichter & Posch (2007): Lehrerinnen und Lehrer erforschen ihren Unterricht","Rolff (2023): Schulentwicklung kompakt"]}
      ]
    }
  }
};
